--
-- PostgreSQL database dump
--

\restrict S714zvZwLKGzuCnELhCWahEe1pfopEqfazfug3RIKy8yBueO6tXh3cUiDSzmXp0

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: orderform_primaries; Type: TABLE; Schema: lh_payproof; Owner: -
--

CREATE TABLE lh_payproof.orderform_primaries (
    orderform_primary_id bigint NOT NULL,
    order_form_id bigint NOT NULL,
    primary_approver_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE orderform_primaries; Type: COMMENT; Schema: lh_payproof; Owner: -
--

COMMENT ON TABLE lh_payproof.orderform_primaries IS 'Maps each order form to exactly one PayProof primary approver profile.';


--
-- Name: COLUMN orderform_primaries.order_form_id; Type: COMMENT; Schema: lh_payproof; Owner: -
--

COMMENT ON COLUMN lh_payproof.orderform_primaries.order_form_id IS 'FK to public.customer_order_forms(ofrm_id). Deleting an order form deletes this mapping (CASCADE).';


--
-- Name: orderform_primaries_orderform_primary_id_seq; Type: SEQUENCE; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.orderform_primaries ALTER COLUMN orderform_primary_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_payproof.orderform_primaries_orderform_primary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orderform_primaries orderform_primaries_pkey; Type: CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.orderform_primaries
    ADD CONSTRAINT orderform_primaries_pkey PRIMARY KEY (orderform_primary_id);


--
-- Name: orderform_primaries uq_orderform_primaries__order_form_id; Type: CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.orderform_primaries
    ADD CONSTRAINT uq_orderform_primaries__order_form_id UNIQUE (order_form_id);


--
-- Name: ix_orderform_primaries__primary_approver_id; Type: INDEX; Schema: lh_payproof; Owner: -
--

CREATE INDEX ix_orderform_primaries__primary_approver_id ON lh_payproof.orderform_primaries USING btree (primary_approver_id);


--
-- Name: orderform_primaries trg_update_orderform_primaries_updated_at; Type: TRIGGER; Schema: lh_payproof; Owner: -
--

CREATE TRIGGER trg_update_orderform_primaries_updated_at BEFORE UPDATE ON lh_payproof.orderform_primaries FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: orderform_primaries fk_orderform_primaries__customer_order_forms; Type: FK CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.orderform_primaries
    ADD CONSTRAINT fk_orderform_primaries__customer_order_forms FOREIGN KEY (order_form_id) REFERENCES public.customer_order_forms(ofrm_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: orderform_primaries fk_orderform_primaries__primary_approvers; Type: FK CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.orderform_primaries
    ADD CONSTRAINT fk_orderform_primaries__primary_approvers FOREIGN KEY (primary_approver_id) REFERENCES lh_payproof.primary_approvers(primary_approver_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: orderform_primaries; Type: ROW SECURITY; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.orderform_primaries ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict S714zvZwLKGzuCnELhCWahEe1pfopEqfazfug3RIKy8yBueO6tXh3cUiDSzmXp0

