--
-- PostgreSQL database dump
--

\restrict SyL49t9lGURUj6Z9BwWHBYjlnnEcdu4qPxEKF9EMfb6hmavRgyLva4XcThtQgMM

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: postprocessing_pipeline_assignments; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.postprocessing_pipeline_assignments (
    postprocessing_pipeline_assignment_id bigint NOT NULL,
    postprocessing_pipeline_id bigint NOT NULL,
    country_code character(2),
    company_id bigint,
    priority integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_postprocessing_pipeline_assignments__country_code_iso CHECK (((country_code IS NULL) OR (btrim((country_code)::text) ~ '^[A-Z]{2}$'::text))),
    CONSTRAINT ck_postprocessing_pipeline_assignments__priority_positive CHECK ((priority > 0))
);


--
-- Name: TABLE postprocessing_pipeline_assignments; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.postprocessing_pipeline_assignments IS 'Deterministic mapping of invoices to pipelines (highest priority wins). Catch-all uses NULL match fields.';


--
-- Name: postprocessing_pipeline_assig_postprocessing_pipeline_assig_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.postprocessing_pipeline_assignments ALTER COLUMN postprocessing_pipeline_assignment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.postprocessing_pipeline_assig_postprocessing_pipeline_assig_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: postprocessing_pipeline_assignments postprocessing_pipeline_assignments_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipeline_assignments
    ADD CONSTRAINT postprocessing_pipeline_assignments_pkey PRIMARY KEY (postprocessing_pipeline_assignment_id);


--
-- Name: ix_postprocessing_pipeline_assignments__match; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_postprocessing_pipeline_assignments__match ON lh_billing_agile.postprocessing_pipeline_assignments USING btree (company_id, country_code, priority);


--
-- Name: uq_postprocessing_pipeline_assignments__priority; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE UNIQUE INDEX uq_postprocessing_pipeline_assignments__priority ON lh_billing_agile.postprocessing_pipeline_assignments USING btree (priority);


--
-- Name: postprocessing_pipeline_assignments trg_update_postprocessing_pipeline_assignments_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_postprocessing_pipeline_assignments_updated_at BEFORE UPDATE ON lh_billing_agile.postprocessing_pipeline_assignments FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: postprocessing_pipeline_assignments fk_postprocessing_pipeline_assignments__companies; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipeline_assignments
    ADD CONSTRAINT fk_postprocessing_pipeline_assignments__companies FOREIGN KEY (company_id) REFERENCES public.companies(cmp_id) ON DELETE RESTRICT;


--
-- Name: postprocessing_pipeline_assignments fk_postprocessing_pipeline_assignments__postprocessing_pipeline; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipeline_assignments
    ADD CONSTRAINT fk_postprocessing_pipeline_assignments__postprocessing_pipeline FOREIGN KEY (postprocessing_pipeline_id) REFERENCES lh_billing_agile.postprocessing_pipelines(postprocessing_pipeline_id) ON DELETE RESTRICT;


--
-- Name: postprocessing_pipeline_assignments; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.postprocessing_pipeline_assignments ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict SyL49t9lGURUj6Z9BwWHBYjlnnEcdu4qPxEKF9EMfb6hmavRgyLva4XcThtQgMM

