--
-- PostgreSQL database dump
--

\restrict Svx2kzjeEpKcEHEzmToxy2JcFzMUYG6ajueJBJi6aXhhXUynLmwEmbMRSrEYrds

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: sent_logs; Type: TABLE; Schema: lh_payproof; Owner: -
--

CREATE TABLE lh_payproof.sent_logs (
    sent_log_id bigint NOT NULL,
    primary_approver_id bigint NOT NULL,
    primary_approver_email character varying(320) NOT NULL,
    year_month date NOT NULL,
    trigger_type text NOT NULL,
    filter_value text,
    correlation_id text NOT NULL,
    send_status text DEFAULT 'sent'::text NOT NULL,
    force_sent boolean DEFAULT false NOT NULL,
    sent_at timestamp with time zone DEFAULT now() NOT NULL,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_sent_logs__primary_approver_email_format CHECK (((length((primary_approver_email)::text) <= 320) AND ((primary_approver_email)::text ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'::text))),
    CONSTRAINT ck_sent_logs__primary_approver_email_not_blank CHECK ((btrim((primary_approver_email)::text) <> ''::text)),
    CONSTRAINT ck_sent_logs__send_status CHECK ((send_status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text]))),
    CONSTRAINT ck_sent_logs__trigger_type CHECK ((trigger_type = ANY (ARRAY['Timer'::text, 'HTTP-CustomerId'::text, 'HTTP-OrderformId'::text])))
);


--
-- Name: TABLE sent_logs; Type: COMMENT; Schema: lh_payproof; Owner: -
--

COMMENT ON TABLE lh_payproof.sent_logs IS 'Tracks PayProof rating sheet sends for idempotence and audit. One record per primary approver per month (plus optional force).';


--
-- Name: sent_logs_sent_log_id_seq; Type: SEQUENCE; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.sent_logs ALTER COLUMN sent_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_payproof.sent_logs_sent_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sent_logs sent_logs_pkey; Type: CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.sent_logs
    ADD CONSTRAINT sent_logs_pkey PRIMARY KEY (sent_log_id);


--
-- Name: sent_logs uq_sent_logs__primary_month_force; Type: CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.sent_logs
    ADD CONSTRAINT uq_sent_logs__primary_month_force UNIQUE (primary_approver_id, year_month, force_sent);


--
-- Name: ix_sent_logs__correlation_id; Type: INDEX; Schema: lh_payproof; Owner: -
--

CREATE INDEX ix_sent_logs__correlation_id ON lh_payproof.sent_logs USING btree (correlation_id);


--
-- Name: ix_sent_logs__primary_approver_id_year_month; Type: INDEX; Schema: lh_payproof; Owner: -
--

CREATE INDEX ix_sent_logs__primary_approver_id_year_month ON lh_payproof.sent_logs USING btree (primary_approver_id, year_month);


--
-- Name: ix_sent_logs__send_status; Type: INDEX; Schema: lh_payproof; Owner: -
--

CREATE INDEX ix_sent_logs__send_status ON lh_payproof.sent_logs USING btree (send_status);


--
-- Name: ix_sent_logs__trigger_type_year_month; Type: INDEX; Schema: lh_payproof; Owner: -
--

CREATE INDEX ix_sent_logs__trigger_type_year_month ON lh_payproof.sent_logs USING btree (trigger_type, year_month);


--
-- Name: sent_logs trg_update_sent_logs_updated_at; Type: TRIGGER; Schema: lh_payproof; Owner: -
--

CREATE TRIGGER trg_update_sent_logs_updated_at BEFORE UPDATE ON lh_payproof.sent_logs FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: sent_logs fk_sent_logs__primary_approvers; Type: FK CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.sent_logs
    ADD CONSTRAINT fk_sent_logs__primary_approvers FOREIGN KEY (primary_approver_id) REFERENCES lh_payproof.primary_approvers(primary_approver_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: sent_logs; Type: ROW SECURITY; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.sent_logs ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict Svx2kzjeEpKcEHEzmToxy2JcFzMUYG6ajueJBJi6aXhhXUynLmwEmbMRSrEYrds

