--
-- PostgreSQL database dump
--

\restrict 1lN4OiivDrqqbazgQFgHp2eVvSSxzxxnMUmLOe5sFo2nnAeDrBC1EJBpIT0LI5s

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoice_external_postings; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.invoice_external_postings (
    invoice_external_posting_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    system text NOT NULL,
    external_id text,
    idempotency_key text NOT NULL,
    posted_at timestamp with time zone,
    metadata jsonb,
    last_error text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_invoice_external_postings__external_id_not_blank CHECK (((external_id IS NULL) OR (btrim(external_id) <> ''::text))),
    CONSTRAINT ck_invoice_external_postings__idempotency_key_not_blank CHECK ((btrim(idempotency_key) <> ''::text)),
    CONSTRAINT ck_invoice_external_postings__last_error_bounded CHECK (((last_error IS NULL) OR (char_length(last_error) <= 4000))),
    CONSTRAINT ck_invoice_external_postings__last_error_not_blank CHECK (((last_error IS NULL) OR (btrim(last_error) <> ''::text))),
    CONSTRAINT ck_invoice_external_postings__posted_consistent CHECK (((external_id IS NULL) = (posted_at IS NULL))),
    CONSTRAINT ck_invoice_external_postings__system_not_blank CHECK ((btrim(system) <> ''::text))
);


--
-- Name: TABLE invoice_external_postings; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.invoice_external_postings IS 'Durable idempotency store for external side-effects (e.g., QuickBooks posting, TIMS registration).';


--
-- Name: COLUMN invoice_external_postings.metadata; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.invoice_external_postings.metadata IS 'Non-secret external posting evidence/identifiers (JSON). Do not store plaintext secrets.';


--
-- Name: invoice_external_postings_invoice_external_posting_id_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_external_postings ALTER COLUMN invoice_external_posting_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.invoice_external_postings_invoice_external_posting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_external_postings invoice_external_postings_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_external_postings
    ADD CONSTRAINT invoice_external_postings_pkey PRIMARY KEY (invoice_external_posting_id);


--
-- Name: invoice_external_postings uq_invoice_external_postings__system_idempotency_key; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_external_postings
    ADD CONSTRAINT uq_invoice_external_postings__system_idempotency_key UNIQUE (system, idempotency_key);


--
-- Name: ix_invoice_external_postings__invoice_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoice_external_postings__invoice_id ON lh_billing_agile.invoice_external_postings USING btree (invoice_id);


--
-- Name: invoice_external_postings trg_update_invoice_external_postings_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_invoice_external_postings_updated_at BEFORE UPDATE ON lh_billing_agile.invoice_external_postings FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: invoice_external_postings fk_invoice_external_postings__invoices; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_external_postings
    ADD CONSTRAINT fk_invoice_external_postings__invoices FOREIGN KEY (invoice_id) REFERENCES lh_billing_agile.invoices(invoice_id) ON DELETE RESTRICT;


--
-- Name: invoice_external_postings; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_external_postings ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict 1lN4OiivDrqqbazgQFgHp2eVvSSxzxxnMUmLOe5sFo2nnAeDrBC1EJBpIT0LI5s

