--
-- PostgreSQL database dump
--

\restrict UTWm3xitTDuWcePRZKBn1b9csPOgaDXpjpu5WiqF5pyZnO5VHh0lSyY5hzGiROD

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: primary_approvers; Type: TABLE; Schema: lh_payproof; Owner: -
--

CREATE TABLE lh_payproof.primary_approvers (
    primary_approver_id bigint NOT NULL,
    primary_email character varying(320) NOT NULL,
    first_name text,
    middle_name text,
    last_name text,
    contact_description text,
    mobile_number text,
    postal_address text,
    street_address_line1 text,
    street_address_line2 text,
    city text,
    state text,
    postal_code text,
    country text,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_primary_approvers__mobile_e164 CHECK (((mobile_number IS NULL) OR (mobile_number ~ '^\+[1-9][0-9]{1,14}$'::text))),
    CONSTRAINT ck_primary_approvers__primary_email_format CHECK (((length((primary_email)::text) <= 320) AND ((primary_email)::text ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'::text))),
    CONSTRAINT ck_primary_approvers__primary_email_not_blank CHECK ((btrim((primary_email)::text) <> ''::text))
);


--
-- Name: TABLE primary_approvers; Type: COMMENT; Schema: lh_payproof; Owner: -
--

COMMENT ON TABLE lh_payproof.primary_approvers IS 'Canonical PayProof primary approver profiles (one per email).';


--
-- Name: COLUMN primary_approvers.primary_email; Type: COMMENT; Schema: lh_payproof; Owner: -
--

COMMENT ON COLUMN lh_payproof.primary_approvers.primary_email IS 'Primary approver email (case-insensitive unique via uq_primary_approvers__primary_email_ci).';


--
-- Name: primary_approvers_primary_approver_id_seq; Type: SEQUENCE; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.primary_approvers ALTER COLUMN primary_approver_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_payproof.primary_approvers_primary_approver_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: primary_approvers primary_approvers_pkey; Type: CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.primary_approvers
    ADD CONSTRAINT primary_approvers_pkey PRIMARY KEY (primary_approver_id);


--
-- Name: uq_primary_approvers__primary_email_ci; Type: INDEX; Schema: lh_payproof; Owner: -
--

CREATE UNIQUE INDEX uq_primary_approvers__primary_email_ci ON lh_payproof.primary_approvers USING btree (lower((primary_email)::text));


--
-- Name: primary_approvers trg_update_primary_approvers_updated_at; Type: TRIGGER; Schema: lh_payproof; Owner: -
--

CREATE TRIGGER trg_update_primary_approvers_updated_at BEFORE UPDATE ON lh_payproof.primary_approvers FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: primary_approvers; Type: ROW SECURITY; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.primary_approvers ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict UTWm3xitTDuWcePRZKBn1b9csPOgaDXpjpu5WiqF5pyZnO5VHh0lSyY5hzGiROD

