--
-- PostgreSQL database dump
--

\restrict A6MZ2KQdhwTGRDMFLS5ZDYLT8rOZZaNrBackqp1RcaVmY6R7OavfGQpDF3tOkCn

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoice_items; Type: TABLE; Schema: lh_tims_emulator; Owner: -
--

CREATE TABLE lh_tims_emulator.invoice_items (
    id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    line_number smallint NOT NULL,
    name text NOT NULL,
    quantity numeric(16,6) NOT NULL,
    unit_price numeric(17,6) NOT NULL,
    total_amount numeric(19,4) NOT NULL,
    hs_code text,
    gtin text,
    discount_value numeric(19,4),
    discount_percent numeric(5,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_invoice_items__discount_percent_range CHECK (((discount_percent IS NULL) OR ((discount_percent >= (0)::numeric) AND (discount_percent <= (100)::numeric)))),
    CONSTRAINT ck_invoice_items__discount_value_non_negative CHECK (((discount_value IS NULL) OR (discount_value >= (0)::numeric))),
    CONSTRAINT ck_invoice_items__gtin_not_blank CHECK (((gtin IS NULL) OR (btrim(gtin) <> ''::text))),
    CONSTRAINT ck_invoice_items__hs_code_not_blank CHECK (((hs_code IS NULL) OR (btrim(hs_code) <> ''::text))),
    CONSTRAINT ck_invoice_items__line_number_non_negative CHECK ((line_number >= 0)),
    CONSTRAINT ck_invoice_items__name_not_blank CHECK ((btrim(name) <> ''::text)),
    CONSTRAINT ck_invoice_items__quantity_non_negative CHECK ((quantity >= (0)::numeric)),
    CONSTRAINT ck_invoice_items__total_amount_non_negative CHECK ((total_amount >= (0)::numeric)),
    CONSTRAINT ck_invoice_items__unit_price_non_negative CHECK ((unit_price >= (0)::numeric))
);


--
-- Name: TABLE invoice_items; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON TABLE lh_tims_emulator.invoice_items IS 'Line items for each invoice';


--
-- Name: COLUMN invoice_items.line_number; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.invoice_items.line_number IS 'Line item number within the invoice.';


--
-- Name: COLUMN invoice_items.hs_code; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.invoice_items.hs_code IS 'HS code for VAT selection';


--
-- Name: COLUMN invoice_items.gtin; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.invoice_items.gtin IS 'Optional GTIN barcode value.';


--
-- Name: COLUMN invoice_items.discount_value; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.invoice_items.discount_value IS 'Optional discount amount applied to the line.';


--
-- Name: COLUMN invoice_items.discount_percent; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.invoice_items.discount_percent IS 'Optional discount percentage applied to the line (0..100).';


--
-- Name: invoice_items_id_seq; Type: SEQUENCE; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE lh_tims_emulator.invoice_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_tims_emulator.invoice_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_items invoice_items_pkey; Type: CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.invoice_items
    ADD CONSTRAINT invoice_items_pkey PRIMARY KEY (id);


--
-- Name: invoice_items uq_invoice_items__invoice_id_line_number; Type: CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.invoice_items
    ADD CONSTRAINT uq_invoice_items__invoice_id_line_number UNIQUE (invoice_id, line_number);


--
-- Name: ix_invoice_items__invoice_id; Type: INDEX; Schema: lh_tims_emulator; Owner: -
--

CREATE INDEX ix_invoice_items__invoice_id ON lh_tims_emulator.invoice_items USING btree (invoice_id);


--
-- Name: invoice_items trg_update_invoice_items_updated_at; Type: TRIGGER; Schema: lh_tims_emulator; Owner: -
--

CREATE TRIGGER trg_update_invoice_items_updated_at BEFORE UPDATE ON lh_tims_emulator.invoice_items FOR EACH ROW EXECUTE FUNCTION lh_tims_emulator.update_updated_at_column();


--
-- Name: invoice_items invoice_items_invoice_id_fkey; Type: FK CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.invoice_items
    ADD CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES lh_tims_emulator.invoices(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict A6MZ2KQdhwTGRDMFLS5ZDYLT8rOZZaNrBackqp1RcaVmY6R7OavfGQpDF3tOkCn

