--
-- PostgreSQL database dump
--

\restrict huUP4wedbgnBLSpiNslGXAAobBZf28OpoaIXaUSUdcQQxX039g2918pkSyNE1cl

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: secondary_approvers; Type: TABLE; Schema: lh_payproof; Owner: -
--

CREATE TABLE lh_payproof.secondary_approvers (
    secondary_approver_id bigint NOT NULL,
    primary_approver_id bigint NOT NULL,
    recipient_type text NOT NULL,
    work_email character varying(320) NOT NULL,
    first_name text,
    middle_name text,
    last_name text,
    contact_description text,
    mobile_number text,
    postal_address text,
    street_address_line1 text,
    street_address_line2 text,
    city text,
    state text,
    postal_code text,
    country text,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_secondary_approvers__mobile_e164 CHECK (((mobile_number IS NULL) OR (mobile_number ~ '^\+[1-9][0-9]{1,14}$'::text))),
    CONSTRAINT ck_secondary_approvers__recipient_type CHECK ((recipient_type = ANY (ARRAY['Cc'::text, 'Bcc'::text]))),
    CONSTRAINT ck_secondary_approvers__work_email_format CHECK (((length((work_email)::text) <= 320) AND ((work_email)::text ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'::text))),
    CONSTRAINT ck_secondary_approvers__work_email_not_blank CHECK ((btrim((work_email)::text) <> ''::text))
);


--
-- Name: TABLE secondary_approvers; Type: COMMENT; Schema: lh_payproof; Owner: -
--

COMMENT ON TABLE lh_payproof.secondary_approvers IS 'PayProof secondary recipients (Cc/Bcc) attached to a primary approver profile.';


--
-- Name: secondary_approvers_secondary_approver_id_seq; Type: SEQUENCE; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.secondary_approvers ALTER COLUMN secondary_approver_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_payproof.secondary_approvers_secondary_approver_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: secondary_approvers secondary_approvers_pkey; Type: CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.secondary_approvers
    ADD CONSTRAINT secondary_approvers_pkey PRIMARY KEY (secondary_approver_id);


--
-- Name: ix_secondary_approvers__recipient_type; Type: INDEX; Schema: lh_payproof; Owner: -
--

CREATE INDEX ix_secondary_approvers__recipient_type ON lh_payproof.secondary_approvers USING btree (recipient_type);


--
-- Name: uq_secondary_approvers__primary_recipient_email_ci; Type: INDEX; Schema: lh_payproof; Owner: -
--

CREATE UNIQUE INDEX uq_secondary_approvers__primary_recipient_email_ci ON lh_payproof.secondary_approvers USING btree (primary_approver_id, recipient_type, lower((work_email)::text));


--
-- Name: secondary_approvers trg_update_secondary_approvers_updated_at; Type: TRIGGER; Schema: lh_payproof; Owner: -
--

CREATE TRIGGER trg_update_secondary_approvers_updated_at BEFORE UPDATE ON lh_payproof.secondary_approvers FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: secondary_approvers fk_secondary_approvers__primary_approvers; Type: FK CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.secondary_approvers
    ADD CONSTRAINT fk_secondary_approvers__primary_approvers FOREIGN KEY (primary_approver_id) REFERENCES lh_payproof.primary_approvers(primary_approver_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: secondary_approvers; Type: ROW SECURITY; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.secondary_approvers ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict huUP4wedbgnBLSpiNslGXAAobBZf28OpoaIXaUSUdcQQxX039g2918pkSyNE1cl

