--
-- PostgreSQL database dump
--

\restrict 4SiGH1aaBq4TRugFAQ6B58cDbvYNeXBsDgOpmuNwYfQSGMasvpC9Zbp1pPXA4b4

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: billing_units; Type: TABLE; Schema: lh_billing; Owner: -
--

CREATE TABLE lh_billing.billing_units (
    billing_unit_id bigint NOT NULL,
    unit_code text NOT NULL,
    unit_description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_billing_units__unit_code_not_blank CHECK ((btrim(unit_code) <> ''::text))
);


--
-- Name: TABLE billing_units; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON TABLE lh_billing.billing_units IS 'Allowed billing units for line items (hour, day, month, fixed, each, etc.). Lookup table to allow extending without schema changes.';


--
-- Name: COLUMN billing_units.unit_code; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.billing_units.unit_code IS 'Short code used in FKs (e.g., month, hour, each)';


--
-- Name: COLUMN billing_units.unit_description; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.billing_units.unit_description IS 'Human-readable description for UI display (e.g., "Monthly billing", "Per-item charge")';


--
-- Name: billing_units_billing_unit_id_seq; Type: SEQUENCE; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.billing_units ALTER COLUMN billing_unit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing.billing_units_billing_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: billing_units billing_units_pkey; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.billing_units
    ADD CONSTRAINT billing_units_pkey PRIMARY KEY (billing_unit_id);


--
-- Name: billing_units uq_billing_units__unit_code; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.billing_units
    ADD CONSTRAINT uq_billing_units__unit_code UNIQUE (unit_code);


--
-- Name: billing_units trg_update_billing_units_updated_at; Type: TRIGGER; Schema: lh_billing; Owner: -
--

CREATE TRIGGER trg_update_billing_units_updated_at BEFORE UPDATE ON lh_billing.billing_units FOR EACH ROW EXECUTE FUNCTION lh_billing.set_updated_at();


--
-- Name: billing_units; Type: ROW SECURITY; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.billing_units ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict 4SiGH1aaBq4TRugFAQ6B58cDbvYNeXBsDgOpmuNwYfQSGMasvpC9Zbp1pPXA4b4

