--
-- PostgreSQL database dump
--

\restrict oNv8RqLfSe1Gqem5NOnwVecVMQ6gd89zHYrWtz1zP0JzxTV08kpFNUe8gDVqvAC

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoice_sequences; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.invoice_sequences (
    invoice_sequence_id bigint NOT NULL,
    context_key text NOT NULL,
    prefix text NOT NULL,
    last_number bigint DEFAULT 0 NOT NULL,
    format text DEFAULT '{prefix}-{year}-{number:06}'::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_invoice_sequences__context_key_not_blank CHECK ((btrim(context_key) <> ''::text)),
    CONSTRAINT ck_invoice_sequences__format_not_blank CHECK ((btrim(format) <> ''::text)),
    CONSTRAINT ck_invoice_sequences__prefix_not_blank CHECK ((btrim(prefix) <> ''::text))
);


--
-- Name: TABLE invoice_sequences; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.invoice_sequences IS 'Invoice number sequences (supports multiple contexts, e.g., per country)';


--
-- Name: COLUMN invoice_sequences.context_key; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.invoice_sequences.context_key IS 'Sequence context: default, KE, RW, etc.';


--
-- Name: COLUMN invoice_sequences.last_number; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.invoice_sequences.last_number IS 'Last assigned invoice number for this context';


--
-- Name: invoice_sequences_invoice_sequence_id_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_sequences ALTER COLUMN invoice_sequence_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.invoice_sequences_invoice_sequence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_sequences invoice_sequences_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_sequences
    ADD CONSTRAINT invoice_sequences_pkey PRIMARY KEY (invoice_sequence_id);


--
-- Name: invoice_sequences uq_invoice_sequences__context_key; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_sequences
    ADD CONSTRAINT uq_invoice_sequences__context_key UNIQUE (context_key);


--
-- Name: invoice_sequences trg_update_invoice_sequences_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_invoice_sequences_updated_at BEFORE UPDATE ON lh_billing_agile.invoice_sequences FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: invoice_sequences; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_sequences ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict oNv8RqLfSe1Gqem5NOnwVecVMQ6gd89zHYrWtz1zP0JzxTV08kpFNUe8gDVqvAC

