--
-- PostgreSQL database dump
--

\restrict Mi2s4Zjnz7Jik543TBS1yU45gLYG06uhG4E6KsuB7HS8iGg7MyQoSbJF4TDJDlx

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoice_taxes; Type: TABLE; Schema: lh_billing; Owner: -
--

CREATE TABLE lh_billing.invoice_taxes (
    invoice_tax_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    tax_type text NOT NULL,
    tax_rate numeric(5,4) NOT NULL,
    taxable_amount numeric(15,2) NOT NULL,
    tax_amount numeric(15,2) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_invoice_taxes__tax_amount_non_negative CHECK ((tax_amount >= (0)::numeric)),
    CONSTRAINT ck_invoice_taxes__tax_rate_non_negative CHECK ((tax_rate >= (0)::numeric)),
    CONSTRAINT ck_invoice_taxes__tax_type_not_blank CHECK ((btrim(tax_type) <> ''::text)),
    CONSTRAINT ck_invoice_taxes__taxable_amount_non_negative CHECK ((taxable_amount >= (0)::numeric))
);


--
-- Name: TABLE invoice_taxes; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON TABLE lh_billing.invoice_taxes IS 'Tax breakdown per invoice';


--
-- Name: COLUMN invoice_taxes.tax_type; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.invoice_taxes.tax_type IS 'Tax type: VAT, GST, WHT, etc.';


--
-- Name: COLUMN invoice_taxes.tax_rate; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.invoice_taxes.tax_rate IS 'Applied tax rate as decimal (e.g., 0.16)';


--
-- Name: invoice_taxes_invoice_tax_id_seq; Type: SEQUENCE; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.invoice_taxes ALTER COLUMN invoice_tax_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing.invoice_taxes_invoice_tax_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_taxes invoice_taxes_pkey; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_taxes
    ADD CONSTRAINT invoice_taxes_pkey PRIMARY KEY (invoice_tax_id);


--
-- Name: ix_invoice_taxes__invoice_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_invoice_taxes__invoice_id ON lh_billing.invoice_taxes USING btree (invoice_id);


--
-- Name: invoice_taxes trg_update_invoice_taxes_updated_at; Type: TRIGGER; Schema: lh_billing; Owner: -
--

CREATE TRIGGER trg_update_invoice_taxes_updated_at BEFORE UPDATE ON lh_billing.invoice_taxes FOR EACH ROW EXECUTE FUNCTION lh_billing.set_updated_at();


--
-- Name: invoice_taxes fk_invoice_taxes__invoices; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_taxes
    ADD CONSTRAINT fk_invoice_taxes__invoices FOREIGN KEY (invoice_id) REFERENCES lh_billing.invoices(invoice_id) ON DELETE RESTRICT;


--
-- Name: invoice_taxes; Type: ROW SECURITY; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.invoice_taxes ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict Mi2s4Zjnz7Jik543TBS1yU45gLYG06uhG4E6KsuB7HS8iGg7MyQoSbJF4TDJDlx

