--
-- PostgreSQL database dump
--

\restrict o07i7HGvpR90AkbqFtz1UVpV30sY2qrAnRWpCCVN2ANM0KsN6J4dXpvAriLDYDt

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: hs_codes; Type: TABLE; Schema: lh_tims_emulator; Owner: -
--

CREATE TABLE lh_tims_emulator.hs_codes (
    id bigint NOT NULL,
    code text NOT NULL,
    description text NOT NULL,
    label text NOT NULL,
    unit text NOT NULL,
    vat text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_hs_codes__code_max_len CHECK ((char_length(code) <= 10)),
    CONSTRAINT ck_hs_codes__code_not_blank CHECK ((btrim(code) <> ''::text)),
    CONSTRAINT ck_hs_codes__description_max_len CHECK ((char_length(description) <= 48)),
    CONSTRAINT ck_hs_codes__description_not_blank CHECK ((btrim(description) <> ''::text)),
    CONSTRAINT ck_hs_codes__label_max_len CHECK ((char_length(label) <= 1)),
    CONSTRAINT ck_hs_codes__label_not_blank CHECK ((btrim(label) <> ''::text)),
    CONSTRAINT ck_hs_codes__unit_max_len CHECK ((char_length(unit) <= 3)),
    CONSTRAINT ck_hs_codes__unit_not_blank CHECK ((btrim(unit) <> ''::text)),
    CONSTRAINT ck_hs_codes__vat_max_len CHECK ((char_length(vat) <= 6)),
    CONSTRAINT ck_hs_codes__vat_not_blank CHECK ((btrim(vat) <> ''::text))
);


--
-- Name: TABLE hs_codes; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON TABLE lh_tims_emulator.hs_codes IS 'Device environment parameters: HS codes, VAT rates, units';


--
-- Name: COLUMN hs_codes.code; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.hs_codes.code IS 'HS code value.';


--
-- Name: COLUMN hs_codes.description; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.hs_codes.description IS 'Short description of the HS code.';


--
-- Name: COLUMN hs_codes.label; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.hs_codes.label IS 'Tax label as returned by the device environment parameters.';


--
-- Name: COLUMN hs_codes.unit; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.hs_codes.unit IS 'Unit of measure code.';


--
-- Name: COLUMN hs_codes.vat; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.hs_codes.vat IS 'VAT rate in basis points as string (e.g., "1600" for 16%)';


--
-- Name: hs_codes_id_seq; Type: SEQUENCE; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE lh_tims_emulator.hs_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_tims_emulator.hs_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hs_codes hs_codes_pkey; Type: CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.hs_codes
    ADD CONSTRAINT hs_codes_pkey PRIMARY KEY (id);


--
-- Name: hs_codes uq_hs_codes__code; Type: CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.hs_codes
    ADD CONSTRAINT uq_hs_codes__code UNIQUE (code);


--
-- Name: ix_hs_codes__label; Type: INDEX; Schema: lh_tims_emulator; Owner: -
--

CREATE INDEX ix_hs_codes__label ON lh_tims_emulator.hs_codes USING btree (label);


--
-- Name: hs_codes trg_update_hs_codes_updated_at; Type: TRIGGER; Schema: lh_tims_emulator; Owner: -
--

CREATE TRIGGER trg_update_hs_codes_updated_at BEFORE UPDATE ON lh_tims_emulator.hs_codes FOR EACH ROW EXECUTE FUNCTION lh_tims_emulator.update_updated_at_column();


--
-- PostgreSQL database dump complete
--

\unrestrict o07i7HGvpR90AkbqFtz1UVpV30sY2qrAnRWpCCVN2ANM0KsN6J4dXpvAriLDYDt

