--
-- PostgreSQL database dump
--

\restrict 7ChijTcJdzLytN8hc7qwacB8JOpRJfLhupwfwsLcYARasFGmRLpnGGEX48v1iZQ

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: global_configurations; Type: TABLE; Schema: lh_billing_system; Owner: -
--

CREATE TABLE lh_billing_system.global_configurations (
    global_configuration_id bigint NOT NULL,
    cfg_key text NOT NULL,
    cfg_value text NOT NULL,
    cfg_description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_global_configurations__cfg_key_not_blank CHECK ((btrim(cfg_key) <> ''::text)),
    CONSTRAINT ck_global_configurations__cfg_value_not_blank CHECK ((btrim(cfg_value) <> ''::text))
);


--
-- Name: TABLE global_configurations; Type: COMMENT; Schema: lh_billing_system; Owner: -
--

COMMENT ON TABLE lh_billing_system.global_configurations IS 'Global default configuration values eligible for use across billing products/services.';


--
-- Name: COLUMN global_configurations.cfg_key; Type: COMMENT; Schema: lh_billing_system; Owner: -
--

COMMENT ON COLUMN lh_billing_system.global_configurations.cfg_key IS 'Configuration key (globally-scoped).';


--
-- Name: COLUMN global_configurations.cfg_value; Type: COMMENT; Schema: lh_billing_system; Owner: -
--

COMMENT ON COLUMN lh_billing_system.global_configurations.cfg_value IS 'Configuration value as text.';


--
-- Name: global_configurations_global_configuration_id_seq; Type: SEQUENCE; Schema: lh_billing_system; Owner: -
--

ALTER TABLE lh_billing_system.global_configurations ALTER COLUMN global_configuration_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_system.global_configurations_global_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: global_configurations global_configurations_pkey; Type: CONSTRAINT; Schema: lh_billing_system; Owner: -
--

ALTER TABLE ONLY lh_billing_system.global_configurations
    ADD CONSTRAINT global_configurations_pkey PRIMARY KEY (global_configuration_id);


--
-- Name: global_configurations uq_global_configurations__cfg_key; Type: CONSTRAINT; Schema: lh_billing_system; Owner: -
--

ALTER TABLE ONLY lh_billing_system.global_configurations
    ADD CONSTRAINT uq_global_configurations__cfg_key UNIQUE (cfg_key);


--
-- Name: ix_global_configurations__cfg_key; Type: INDEX; Schema: lh_billing_system; Owner: -
--

CREATE INDEX ix_global_configurations__cfg_key ON lh_billing_system.global_configurations USING btree (cfg_key);


--
-- Name: global_configurations trg_update_global_configurations_updated_at; Type: TRIGGER; Schema: lh_billing_system; Owner: -
--

CREATE TRIGGER trg_update_global_configurations_updated_at BEFORE UPDATE ON lh_billing_system.global_configurations FOR EACH ROW EXECUTE FUNCTION lh_billing_system.set_updated_at();


--
-- Name: global_configurations; Type: ROW SECURITY; Schema: lh_billing_system; Owner: -
--

ALTER TABLE lh_billing_system.global_configurations ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict 7ChijTcJdzLytN8hc7qwacB8JOpRJfLhupwfwsLcYARasFGmRLpnGGEX48v1iZQ

