--
-- PostgreSQL database dump
--

\restrict TQf9lp41NDcmUkClJThxFn2bS4knaRcSXLvq1nQ561ubGBZVHWSREJ61cFc8g0A

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoice_line_items; Type: TABLE; Schema: lh_billing; Owner: -
--

CREATE TABLE lh_billing.invoice_line_items (
    invoice_line_item_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    ofast_id bigint NOT NULL,
    odrl_id bigint NOT NULL,
    res_id bigint NOT NULL,
    resource_name text NOT NULL,
    role_level text NOT NULL,
    role_description text NOT NULL,
    service_code text,
    unit_code text NOT NULL,
    quantity numeric(12,4) NOT NULL,
    unit_fee numeric(15,2) NOT NULL,
    discount_percent numeric(5,2) DEFAULT 0 NOT NULL,
    final_unit_fee numeric(15,2) NOT NULL,
    line_total numeric(15,2) NOT NULL,
    is_prorated boolean DEFAULT false NOT NULL,
    proration_days integer,
    proration_total_days integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_invoice_line_items__discount_percent_valid CHECK (((discount_percent >= (0)::numeric) AND (discount_percent <= (100)::numeric))),
    CONSTRAINT ck_invoice_line_items__final_unit_fee_non_negative CHECK ((final_unit_fee >= (0)::numeric)),
    CONSTRAINT ck_invoice_line_items__line_total_non_negative CHECK ((line_total >= (0)::numeric)),
    CONSTRAINT ck_invoice_line_items__quantity_positive CHECK ((quantity > (0)::numeric)),
    CONSTRAINT ck_invoice_line_items__resource_name_not_blank CHECK ((btrim(resource_name) <> ''::text)),
    CONSTRAINT ck_invoice_line_items__role_description_not_blank CHECK ((btrim(role_description) <> ''::text)),
    CONSTRAINT ck_invoice_line_items__role_level_not_blank CHECK ((btrim(role_level) <> ''::text)),
    CONSTRAINT ck_invoice_line_items__unit_fee_non_negative CHECK ((unit_fee >= (0)::numeric))
);


--
-- Name: TABLE invoice_line_items; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON TABLE lh_billing.invoice_line_items IS 'Detailed line items for each invoice (denormalized for accuracy)';


--
-- Name: COLUMN invoice_line_items.resource_name; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.invoice_line_items.resource_name IS 'Resource name at time of invoice (denormalized)';


--
-- Name: COLUMN invoice_line_items.unit_code; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.invoice_line_items.unit_code IS 'Billing unit code (FK to billing_units), e.g., month, day, hour, fixed';


--
-- Name: COLUMN invoice_line_items.final_unit_fee; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.invoice_line_items.final_unit_fee IS 'Final fee per unit after discount (copied at invoice time for accuracy)';


--
-- Name: COLUMN invoice_line_items.is_prorated; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.invoice_line_items.is_prorated IS 'True if this line item quantity includes proration (e.g., partial month)';


--
-- Name: invoice_line_items_invoice_line_item_id_seq; Type: SEQUENCE; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.invoice_line_items ALTER COLUMN invoice_line_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing.invoice_line_items_invoice_line_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_line_items invoice_line_items_pkey; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_line_items
    ADD CONSTRAINT invoice_line_items_pkey PRIMARY KEY (invoice_line_item_id);


--
-- Name: ix_invoice_line_items__invoice_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_invoice_line_items__invoice_id ON lh_billing.invoice_line_items USING btree (invoice_id);


--
-- Name: invoice_line_items trg_update_invoice_line_items_updated_at; Type: TRIGGER; Schema: lh_billing; Owner: -
--

CREATE TRIGGER trg_update_invoice_line_items_updated_at BEFORE UPDATE ON lh_billing.invoice_line_items FOR EACH ROW EXECUTE FUNCTION lh_billing.set_updated_at();


--
-- Name: invoice_line_items fk_invoice_line_items__billing_units; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_line_items
    ADD CONSTRAINT fk_invoice_line_items__billing_units FOREIGN KEY (unit_code) REFERENCES lh_billing.billing_units(unit_code) ON DELETE RESTRICT;


--
-- Name: invoice_line_items fk_invoice_line_items__invoices; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_line_items
    ADD CONSTRAINT fk_invoice_line_items__invoices FOREIGN KEY (invoice_id) REFERENCES lh_billing.invoices(invoice_id) ON DELETE RESTRICT;


--
-- Name: invoice_line_items fk_invoice_line_items__orderform_assignments; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_line_items
    ADD CONSTRAINT fk_invoice_line_items__orderform_assignments FOREIGN KEY (ofast_id) REFERENCES public.orderform_assignments(ofast_id) ON DELETE RESTRICT;


--
-- Name: invoice_line_items fk_invoice_line_items__orderform_ordered_roles; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_line_items
    ADD CONSTRAINT fk_invoice_line_items__orderform_ordered_roles FOREIGN KEY (odrl_id) REFERENCES public.orderform_ordered_roles(odrl_id) ON DELETE RESTRICT;


--
-- Name: invoice_line_items fk_invoice_line_items__resources; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_line_items
    ADD CONSTRAINT fk_invoice_line_items__resources FOREIGN KEY (res_id) REFERENCES public.resources(res_id) ON DELETE RESTRICT;


--
-- Name: invoice_line_items; Type: ROW SECURITY; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.invoice_line_items ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict TQf9lp41NDcmUkClJThxFn2bS4knaRcSXLvq1nQ561ubGBZVHWSREJ61cFc8g0A

