--
-- PostgreSQL database dump
--

\restrict kk8CR52TJ5tY2WfaBTCKhfi6Jmt2Ej936nurhIqGmRLkElG3GkfFhHdK1IJoQhc

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: postprocessing_pipeline_steps; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.postprocessing_pipeline_steps (
    postprocessing_pipeline_step_id bigint NOT NULL,
    postprocessing_pipeline_version_id bigint NOT NULL,
    step_order integer NOT NULL,
    step_key text NOT NULL,
    step_config jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_postprocessing_pipeline_steps__step_key_not_blank CHECK ((btrim(step_key) <> ''::text)),
    CONSTRAINT ck_postprocessing_pipeline_steps__step_order_positive CHECK ((step_order > 0))
);


--
-- Name: TABLE postprocessing_pipeline_steps; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.postprocessing_pipeline_steps IS 'Ordered steps for a specific pipeline version.';


--
-- Name: COLUMN postprocessing_pipeline_steps.step_key; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.postprocessing_pipeline_steps.step_key IS 'Capability-based step identifier implemented in code (e.g., tims.register_invoice).';


--
-- Name: postprocessing_pipeline_steps_postprocessing_pipeline_step__seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.postprocessing_pipeline_steps ALTER COLUMN postprocessing_pipeline_step_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.postprocessing_pipeline_steps_postprocessing_pipeline_step__seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: postprocessing_pipeline_steps postprocessing_pipeline_steps_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipeline_steps
    ADD CONSTRAINT postprocessing_pipeline_steps_pkey PRIMARY KEY (postprocessing_pipeline_step_id);


--
-- Name: postprocessing_pipeline_steps uq_postprocessing_pipeline_steps__version_step_order; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipeline_steps
    ADD CONSTRAINT uq_postprocessing_pipeline_steps__version_step_order UNIQUE (postprocessing_pipeline_version_id, step_order);


--
-- Name: ix_postprocessing_pipeline_steps__version_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_postprocessing_pipeline_steps__version_id ON lh_billing_agile.postprocessing_pipeline_steps USING btree (postprocessing_pipeline_version_id);


--
-- Name: postprocessing_pipeline_steps trg_update_postprocessing_pipeline_steps_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_postprocessing_pipeline_steps_updated_at BEFORE UPDATE ON lh_billing_agile.postprocessing_pipeline_steps FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: postprocessing_pipeline_steps fk_postprocessing_pipeline_steps__postprocessing_pipeline_versi; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipeline_steps
    ADD CONSTRAINT fk_postprocessing_pipeline_steps__postprocessing_pipeline_versi FOREIGN KEY (postprocessing_pipeline_version_id) REFERENCES lh_billing_agile.postprocessing_pipeline_versions(postprocessing_pipeline_version_id) ON DELETE RESTRICT;


--
-- Name: postprocessing_pipeline_steps; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.postprocessing_pipeline_steps ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict kk8CR52TJ5tY2WfaBTCKhfi6Jmt2Ej936nurhIqGmRLkElG3GkfFhHdK1IJoQhc

