--
-- PostgreSQL database dump
--

\restrict vAcVnk1iXA9ApmsxgLRXcAuCxFNM8OMOObr9P4zhQkinebGeD3NaDVad2zbLCVE

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: postprocessing_pipeline_versions; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.postprocessing_pipeline_versions (
    postprocessing_pipeline_version_id bigint NOT NULL,
    postprocessing_pipeline_id bigint NOT NULL,
    version_number integer NOT NULL,
    definition_checksum text NOT NULL,
    approved_at timestamp with time zone,
    approved_by text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_postprocessing_pipeline_versions__approval_consistent CHECK (((approved_at IS NULL) = (approved_by IS NULL))),
    CONSTRAINT ck_postprocessing_pipeline_versions__approved_by_not_blank CHECK (((approved_by IS NULL) OR (btrim(approved_by) <> ''::text))),
    CONSTRAINT ck_postprocessing_pipeline_versions__definition_checksum_not_bl CHECK ((btrim(definition_checksum) <> ''::text)),
    CONSTRAINT ck_postprocessing_pipeline_versions__version_number_positive CHECK ((version_number > 0))
);


--
-- Name: TABLE postprocessing_pipeline_versions; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.postprocessing_pipeline_versions IS 'Versioned pipeline definitions (snapshot-able).';


--
-- Name: COLUMN postprocessing_pipeline_versions.definition_checksum; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.postprocessing_pipeline_versions.definition_checksum IS 'Checksum of the pipeline definition (tamper/change detection).';


--
-- Name: postprocessing_pipeline_versi_postprocessing_pipeline_versi_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.postprocessing_pipeline_versions ALTER COLUMN postprocessing_pipeline_version_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.postprocessing_pipeline_versi_postprocessing_pipeline_versi_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: postprocessing_pipeline_versions postprocessing_pipeline_versions_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipeline_versions
    ADD CONSTRAINT postprocessing_pipeline_versions_pkey PRIMARY KEY (postprocessing_pipeline_version_id);


--
-- Name: postprocessing_pipeline_versions uq_postprocessing_pipeline_versions__pipeline_version; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipeline_versions
    ADD CONSTRAINT uq_postprocessing_pipeline_versions__pipeline_version UNIQUE (postprocessing_pipeline_id, version_number);


--
-- Name: ix_postprocessing_pipeline_versions__pipeline_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_postprocessing_pipeline_versions__pipeline_id ON lh_billing_agile.postprocessing_pipeline_versions USING btree (postprocessing_pipeline_id);


--
-- Name: postprocessing_pipeline_versions trg_update_postprocessing_pipeline_versions_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_postprocessing_pipeline_versions_updated_at BEFORE UPDATE ON lh_billing_agile.postprocessing_pipeline_versions FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: postprocessing_pipeline_versions fk_postprocessing_pipeline_versions__postprocessing_pipelines; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipeline_versions
    ADD CONSTRAINT fk_postprocessing_pipeline_versions__postprocessing_pipelines FOREIGN KEY (postprocessing_pipeline_id) REFERENCES lh_billing_agile.postprocessing_pipelines(postprocessing_pipeline_id) ON DELETE RESTRICT;


--
-- Name: postprocessing_pipeline_versions; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.postprocessing_pipeline_versions ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict vAcVnk1iXA9ApmsxgLRXcAuCxFNM8OMOObr9P4zhQkinebGeD3NaDVad2zbLCVE

