--
-- PostgreSQL database dump
--

\restrict Jhq6bxl4V3loKx7GnqqYA0WwuNDYKQXfMc18QV5Lh9MUGaMGfO7R5kkIcGHmWtQ

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: supabase_migrations; Owner: -
--

COPY supabase_migrations.schema_migrations (version, statements, name, created_by, idempotency_key, rollback) FROM stdin;
20260106014014	{"-- Migration: Create payproof_inbound_delta_tokens table\n-- Purpose: Store Microsoft Graph delta tokens for inbox polling\n-- Schema: lh_system\n\nBEGIN;\n\nSET search_path = lh_system, public, pg_catalog;\n\n-- Table: payproof_inbound_delta_tokens\n-- Stores delta tokens for each mailbox to enable incremental polling via Graph delta API\n\nCREATE TABLE IF NOT EXISTS lh_system.payproof_inbound_delta_tokens\n(\n    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n    mailbox_address text NOT NULL,\n    delta_token text NULL,\n    last_polled_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    CONSTRAINT payproof_inbound_delta_tokens_pkey PRIMARY KEY (id),\n    CONSTRAINT uq_payproof_inbound_delta_tokens_mailbox UNIQUE (mailbox_address)\n);\n\n-- Index for mailbox lookups\nCREATE INDEX IF NOT EXISTS idx_payproof_inbound_delta_tokens_mailbox\n    ON lh_system.payproof_inbound_delta_tokens USING btree (mailbox_address)\n    WITH (fillfactor = 100, deduplicate_items = true);\n\n-- Trigger for updated_at\nCREATE TRIGGER trg_update_payproof_inbound_delta_tokens_updated_at\n    BEFORE UPDATE ON lh_system.payproof_inbound_delta_tokens\n    FOR EACH ROW\n    EXECUTE FUNCTION public.update_updated_at_column();\n\n-- Enable RLS (row level security)\nALTER TABLE lh_system.payproof_inbound_delta_tokens ENABLE ROW LEVEL SECURITY;\n\n-- Comments\nCOMMENT ON TABLE lh_system.payproof_inbound_delta_tokens IS\n    'Stores Microsoft Graph delta tokens for incremental inbox polling. One record per mailbox address.';\n\nCOMMENT ON COLUMN lh_system.payproof_inbound_delta_tokens.id IS\n    'Primary key, auto-incremented.';\n\nCOMMENT ON COLUMN lh_system.payproof_inbound_delta_tokens.mailbox_address IS\n    'Email address of the mailbox being polled (unique per mailbox).';\n\nCOMMENT ON COLUMN lh_system.payproof_inbound_delta_tokens.delta_token IS\n    'Microsoft Graph delta token for incremental querying. NULL on first poll (no previous token).';\n\nCOMMENT ON COLUMN lh_system.payproof_inbound_delta_tokens.last_polled_at IS\n    'UTC timestamp of the last successful poll operation.';\n\nCOMMENT ON COLUMN lh_system.payproof_inbound_delta_tokens.created_at IS\n    'UTC timestamp when this record was created.';\n\nCOMMENT ON COLUMN lh_system.payproof_inbound_delta_tokens.updated_at IS\n    'UTC timestamp when this record was last updated (automatically maintained by trigger).';\n\nCOMMIT;"}	create_inbound_delta_tokens	collins.munene@shipht.it	\N	\N
\.


--
-- PostgreSQL database dump complete
--

\unrestrict Jhq6bxl4V3loKx7GnqqYA0WwuNDYKQXfMc18QV5Lh9MUGaMGfO7R5kkIcGHmWtQ

