--
-- PostgreSQL database dump
--

\restrict P4GNOPH3dJeMClQABLamgDvV9cQgoxgEs6JK8nHhqQiF7Zxrn3DY41FmdTSS5l1

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: postprocessing_pipelines; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.postprocessing_pipelines (
    postprocessing_pipeline_id bigint NOT NULL,
    pipeline_name text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_postprocessing_pipelines__pipeline_name_not_blank CHECK ((btrim(pipeline_name) <> ''::text))
);


--
-- Name: TABLE postprocessing_pipelines; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.postprocessing_pipelines IS 'Postprocessing pipelines (named, activatable) used by Phase 3 rules engine.';


--
-- Name: COLUMN postprocessing_pipelines.pipeline_name; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.postprocessing_pipelines.pipeline_name IS 'Unique pipeline identifier (e.g., no_postprocessing, kenya_default).';


--
-- Name: postprocessing_pipelines_postprocessing_pipeline_id_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.postprocessing_pipelines ALTER COLUMN postprocessing_pipeline_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.postprocessing_pipelines_postprocessing_pipeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: postprocessing_pipelines postprocessing_pipelines_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipelines
    ADD CONSTRAINT postprocessing_pipelines_pkey PRIMARY KEY (postprocessing_pipeline_id);


--
-- Name: postprocessing_pipelines uq_postprocessing_pipelines__pipeline_name; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.postprocessing_pipelines
    ADD CONSTRAINT uq_postprocessing_pipelines__pipeline_name UNIQUE (pipeline_name);


--
-- Name: postprocessing_pipelines trg_update_postprocessing_pipelines_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_postprocessing_pipelines_updated_at BEFORE UPDATE ON lh_billing_agile.postprocessing_pipelines FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: postprocessing_pipelines; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.postprocessing_pipelines ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict P4GNOPH3dJeMClQABLamgDvV9cQgoxgEs6JK8nHhqQiF7Zxrn3DY41FmdTSS5l1

