--
-- PostgreSQL database dump
--

\restrict mBKLCo7EG7Sjqjcw2RyMJI25lX5eg4Faceol9upiDGzFgNszDzpc4EuGOffWYbS

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: billing_contacts; Type: TABLE; Schema: lh_billing; Owner: -
--

CREATE TABLE lh_billing.billing_contacts (
    billing_contact_id bigint NOT NULL,
    cmp_id bigint,
    cctr_id bigint,
    ofrm_id bigint,
    contact_type text NOT NULL,
    email character varying(320) NOT NULL,
    name text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_billing_contacts__contact_type CHECK ((contact_type = ANY (ARRAY['Primary'::text, 'Cc'::text, 'Bcc'::text]))),
    CONSTRAINT ck_billing_contacts__email_format CHECK (((email)::text ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'::text)),
    CONSTRAINT ck_billing_contacts__email_not_blank CHECK ((btrim((email)::text) <> ''::text)),
    CONSTRAINT ck_billing_contacts__scope_xor CHECK ((((cmp_id IS NOT NULL) AND (cctr_id IS NULL) AND (ofrm_id IS NULL)) OR ((cmp_id IS NULL) AND (cctr_id IS NOT NULL) AND (ofrm_id IS NULL)) OR ((cmp_id IS NULL) AND (cctr_id IS NULL) AND (ofrm_id IS NOT NULL))))
);


--
-- Name: TABLE billing_contacts; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON TABLE lh_billing.billing_contacts IS 'Invoice recipients scoped to company, contract, or order form level. Resolution precedence: order form → contract → company.';


--
-- Name: COLUMN billing_contacts.contact_type; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.billing_contacts.contact_type IS 'Recipient type: Primary (To recipient), Cc, or Bcc';


--
-- Name: COLUMN billing_contacts.email; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.billing_contacts.email IS 'Email address (validated format, RFC 5321 max length)';


--
-- Name: billing_contacts_billing_contact_id_seq; Type: SEQUENCE; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.billing_contacts ALTER COLUMN billing_contact_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing.billing_contacts_billing_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: billing_contacts billing_contacts_pkey; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.billing_contacts
    ADD CONSTRAINT billing_contacts_pkey PRIMARY KEY (billing_contact_id);


--
-- Name: ix_billing_contacts__cctr_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_billing_contacts__cctr_id ON lh_billing.billing_contacts USING btree (cctr_id);


--
-- Name: ix_billing_contacts__cmp_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_billing_contacts__cmp_id ON lh_billing.billing_contacts USING btree (cmp_id);


--
-- Name: ix_billing_contacts__ofrm_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_billing_contacts__ofrm_id ON lh_billing.billing_contacts USING btree (ofrm_id);


--
-- Name: billing_contacts trg_update_billing_contacts_updated_at; Type: TRIGGER; Schema: lh_billing; Owner: -
--

CREATE TRIGGER trg_update_billing_contacts_updated_at BEFORE UPDATE ON lh_billing.billing_contacts FOR EACH ROW EXECUTE FUNCTION lh_billing.set_updated_at();


--
-- Name: billing_contacts fk_billing_contacts__companies; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.billing_contacts
    ADD CONSTRAINT fk_billing_contacts__companies FOREIGN KEY (cmp_id) REFERENCES public.companies(cmp_id) ON DELETE RESTRICT;


--
-- Name: billing_contacts fk_billing_contacts__customer_contracts; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.billing_contacts
    ADD CONSTRAINT fk_billing_contacts__customer_contracts FOREIGN KEY (cctr_id) REFERENCES public.customer_contracts(cctr_id) ON DELETE RESTRICT;


--
-- Name: billing_contacts fk_billing_contacts__customer_order_forms; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.billing_contacts
    ADD CONSTRAINT fk_billing_contacts__customer_order_forms FOREIGN KEY (ofrm_id) REFERENCES public.customer_order_forms(ofrm_id) ON DELETE RESTRICT;


--
-- Name: billing_contacts; Type: ROW SECURITY; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.billing_contacts ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict mBKLCo7EG7Sjqjcw2RyMJI25lX5eg4Faceol9upiDGzFgNszDzpc4EuGOffWYbS

