--
-- PostgreSQL database dump
--

\restrict ZHdpL1FBEA3i4QfskyNthIFrzdRLKhImu9Co3teEPjPKWTYZ2oMcbcfe3vr6yfC

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: orderform_primary_gaps; Type: TABLE; Schema: lh_payproof; Owner: -
--

CREATE TABLE lh_payproof.orderform_primary_gaps (
    orderform_primary_gap_id bigint NOT NULL,
    order_form_id bigint NOT NULL,
    orderform_alternate_contact_id bigint,
    reason text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_orderform_primary_gaps__reason_not_blank CHECK ((btrim(reason) <> ''::text))
);


--
-- Name: TABLE orderform_primary_gaps; Type: COMMENT; Schema: lh_payproof; Owner: -
--

COMMENT ON TABLE lh_payproof.orderform_primary_gaps IS 'Diagnostics/audit for order forms missing PayProof primary mappings (gap tracking).';


--
-- Name: orderform_primary_gaps_orderform_primary_gap_id_seq; Type: SEQUENCE; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.orderform_primary_gaps ALTER COLUMN orderform_primary_gap_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_payproof.orderform_primary_gaps_orderform_primary_gap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orderform_primary_gaps orderform_primary_gaps_pkey; Type: CONSTRAINT; Schema: lh_payproof; Owner: -
--

ALTER TABLE ONLY lh_payproof.orderform_primary_gaps
    ADD CONSTRAINT orderform_primary_gaps_pkey PRIMARY KEY (orderform_primary_gap_id);


--
-- Name: orderform_primary_gaps trg_update_orderform_primary_gaps_updated_at; Type: TRIGGER; Schema: lh_payproof; Owner: -
--

CREATE TRIGGER trg_update_orderform_primary_gaps_updated_at BEFORE UPDATE ON lh_payproof.orderform_primary_gaps FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: orderform_primary_gaps; Type: ROW SECURITY; Schema: lh_payproof; Owner: -
--

ALTER TABLE lh_payproof.orderform_primary_gaps ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict ZHdpL1FBEA3i4QfskyNthIFrzdRLKhImu9Co3teEPjPKWTYZ2oMcbcfe3vr6yfC

