--
-- PostgreSQL database dump
--

\restrict H5LhgYAVRdtnZkaOgTuiJ2oXqwW7mE7tk0B9RQic5P9Ymv3Jq75IXBg3YaC7zK0

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoices; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.invoices (
    invoice_id bigint NOT NULL,
    inv_prfx_id text,
    cmp_id bigint NOT NULL,
    cctr_id bigint,
    invoice_grouping text NOT NULL,
    billing_group_key text NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    currency character(3) NOT NULL,
    subtotal numeric(15,2) NOT NULL,
    tax_total numeric(15,2) NOT NULL,
    grand_total numeric(15,2) NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    trigger_type text NOT NULL,
    correlation_id text NOT NULL,
    force_sent boolean DEFAULT false NOT NULL,
    is_dry_run boolean DEFAULT false NOT NULL,
    test_recipients text[],
    generated_at timestamp with time zone,
    sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_invoices__amounts_non_negative CHECK (((subtotal >= (0)::numeric) AND (tax_total >= (0)::numeric) AND (grand_total >= (0)::numeric))),
    CONSTRAINT ck_invoices__billing_group_key_not_blank CHECK ((btrim(billing_group_key) <> ''::text)),
    CONSTRAINT ck_invoices__correlation_id_not_blank CHECK ((btrim(correlation_id) <> ''::text)),
    CONSTRAINT ck_invoices__currency_not_blank CHECK ((btrim((currency)::text) <> ''::text)),
    CONSTRAINT ck_invoices__dry_run_consistency CHECK ((((is_dry_run = true) AND (status = 'dry_run'::text)) OR ((is_dry_run = false) AND (status <> 'dry_run'::text)))),
    CONSTRAINT ck_invoices__inv_prfx_id_not_blank CHECK (((inv_prfx_id IS NULL) OR (btrim(inv_prfx_id) <> ''::text))),
    CONSTRAINT ck_invoices__invoice_grouping CHECK ((invoice_grouping = ANY (ARRAY['per_order_form'::text, 'per_company'::text]))),
    CONSTRAINT ck_invoices__period_valid CHECK ((period_end >= period_start)),
    CONSTRAINT ck_invoices__status CHECK ((status = ANY (ARRAY['draft'::text, 'generated'::text, 'sent'::text, 'failed_generate'::text, 'failed_send'::text, 'void'::text, 'dry_run'::text]))),
    CONSTRAINT ck_invoices__trigger_type CHECK ((trigger_type = ANY (ARRAY['Timer'::text, 'HTTP-CompanyId'::text, 'HTTP-ContractId'::text, 'HTTP-OrderformId-Admin'::text])))
);


--
-- Name: TABLE invoices; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.invoices IS 'Primary invoice records with idempotency enforcement';


--
-- Name: COLUMN invoices.inv_prfx_id; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.invoices.inv_prfx_id IS 'Human-readable invoice ID (e.g., INV-2024-009001)';


--
-- Name: COLUMN invoices.invoice_grouping; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.invoices.invoice_grouping IS 'Grouping mode: per_order_form or per_company';


--
-- Name: COLUMN invoices.billing_group_key; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.invoices.billing_group_key IS 'Idempotency grouping key (e.g., cmp:123 or ofrm:456)';


--
-- Name: COLUMN invoices.status; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.invoices.status IS 'Lifecycle status: draft, generated, sent, failed_generate, failed_send, void, dry_run';


--
-- Name: COLUMN invoices.is_dry_run; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.invoices.is_dry_run IS 'True if this is a test/dry-run invoice (does not block real invoices)';


--
-- Name: invoices_invoice_id_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoices ALTER COLUMN invoice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.invoices_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (invoice_id);


--
-- Name: invoices uq_invoices__inv_prfx_id; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoices
    ADD CONSTRAINT uq_invoices__inv_prfx_id UNIQUE (inv_prfx_id);


--
-- Name: ix_invoices__cctr_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoices__cctr_id ON lh_billing_agile.invoices USING btree (cctr_id);


--
-- Name: ix_invoices__cmp_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoices__cmp_id ON lh_billing_agile.invoices USING btree (cmp_id);


--
-- Name: ix_invoices__is_dry_run; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoices__is_dry_run ON lh_billing_agile.invoices USING btree (is_dry_run) WHERE (is_dry_run = true);


--
-- Name: ix_invoices__period; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoices__period ON lh_billing_agile.invoices USING btree (period_start, period_end);


--
-- Name: ix_invoices__status; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoices__status ON lh_billing_agile.invoices USING btree (status);


--
-- Name: uq_invoices__idempotency; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE UNIQUE INDEX uq_invoices__idempotency ON lh_billing_agile.invoices USING btree (billing_group_key, invoice_grouping, period_start, period_end, currency) WHERE ((is_dry_run = false) AND (status <> 'void'::text) AND (force_sent = false));


--
-- Name: invoices trg_update_invoices_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_invoices_updated_at BEFORE UPDATE ON lh_billing_agile.invoices FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: invoices fk_invoices__companies; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoices
    ADD CONSTRAINT fk_invoices__companies FOREIGN KEY (cmp_id) REFERENCES public.companies(cmp_id) ON DELETE RESTRICT;


--
-- Name: invoices fk_invoices__customer_contracts; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoices
    ADD CONSTRAINT fk_invoices__customer_contracts FOREIGN KEY (cctr_id) REFERENCES public.customer_contracts(cctr_id) ON DELETE RESTRICT;


--
-- Name: invoices; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoices ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict H5LhgYAVRdtnZkaOgTuiJ2oXqwW7mE7tk0B9RQic5P9Ymv3Jq75IXBg3YaC7zK0

