--
-- PostgreSQL database dump
--

\restrict WtSdoo46IalYqIUYCeXgEFN8C5jSRxyU3ubr9mXca8nUH8Jcovrn734ATDQh5t6

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoice_postprocessing_queue; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.invoice_postprocessing_queue (
    invoice_postprocessing_queue_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    pipeline_version_id bigint NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    next_attempt_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    max_attempts integer DEFAULT 10 NOT NULL,
    locked_at timestamp with time zone,
    locked_by text,
    blocked_reason text,
    last_error text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_invoice_postprocessing_queue__attempt_count_non_negative CHECK ((attempt_count >= 0)),
    CONSTRAINT ck_invoice_postprocessing_queue__blocked_reason_required CHECK (((status <> 'blocked'::text) OR (btrim(COALESCE(blocked_reason, ''::text)) <> ''::text))),
    CONSTRAINT ck_invoice_postprocessing_queue__last_error_bounded CHECK (((last_error IS NULL) OR (char_length(last_error) <= 4000))),
    CONSTRAINT ck_invoice_postprocessing_queue__last_error_not_blank CHECK (((last_error IS NULL) OR (btrim(last_error) <> ''::text))),
    CONSTRAINT ck_invoice_postprocessing_queue__lock_consistent CHECK (((locked_at IS NULL) = (locked_by IS NULL))),
    CONSTRAINT ck_invoice_postprocessing_queue__locked_by_not_blank CHECK (((locked_by IS NULL) OR (btrim(locked_by) <> ''::text))),
    CONSTRAINT ck_invoice_postprocessing_queue__max_attempts_positive CHECK ((max_attempts > 0)),
    CONSTRAINT ck_invoice_postprocessing_queue__status CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'blocked'::text, 'completed'::text])))
);


--
-- Name: TABLE invoice_postprocessing_queue; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.invoice_postprocessing_queue IS 'Phase 3 operational queue (one row per invoice) supporting retries, locking (SKIP LOCKED), and pipeline version snapshotting.';


--
-- Name: invoice_postprocessing_queue_invoice_postprocessing_queue_i_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_postprocessing_queue ALTER COLUMN invoice_postprocessing_queue_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.invoice_postprocessing_queue_invoice_postprocessing_queue_i_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_postprocessing_queue invoice_postprocessing_queue_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_postprocessing_queue
    ADD CONSTRAINT invoice_postprocessing_queue_pkey PRIMARY KEY (invoice_postprocessing_queue_id);


--
-- Name: invoice_postprocessing_queue uq_invoice_postprocessing_queue__invoice_id; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_postprocessing_queue
    ADD CONSTRAINT uq_invoice_postprocessing_queue__invoice_id UNIQUE (invoice_id);


--
-- Name: ix_invoice_postprocessing_queue__pipeline_version_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoice_postprocessing_queue__pipeline_version_id ON lh_billing_agile.invoice_postprocessing_queue USING btree (pipeline_version_id);


--
-- Name: ix_invoice_postprocessing_queue__polling; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoice_postprocessing_queue__polling ON lh_billing_agile.invoice_postprocessing_queue USING btree (status, next_attempt_at, invoice_postprocessing_queue_id);


--
-- Name: invoice_postprocessing_queue trg_update_invoice_postprocessing_queue_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_invoice_postprocessing_queue_updated_at BEFORE UPDATE ON lh_billing_agile.invoice_postprocessing_queue FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: invoice_postprocessing_queue fk_invoice_postprocessing_queue__invoices; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_postprocessing_queue
    ADD CONSTRAINT fk_invoice_postprocessing_queue__invoices FOREIGN KEY (invoice_id) REFERENCES lh_billing_agile.invoices(invoice_id) ON DELETE RESTRICT;


--
-- Name: invoice_postprocessing_queue fk_invoice_postprocessing_queue__postprocessing_pipeline_versio; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_postprocessing_queue
    ADD CONSTRAINT fk_invoice_postprocessing_queue__postprocessing_pipeline_versio FOREIGN KEY (pipeline_version_id) REFERENCES lh_billing_agile.postprocessing_pipeline_versions(postprocessing_pipeline_version_id) ON DELETE RESTRICT;


--
-- Name: invoice_postprocessing_queue; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_postprocessing_queue ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict WtSdoo46IalYqIUYCeXgEFN8C5jSRxyU3ubr9mXca8nUH8Jcovrn734ATDQh5t6

