--
-- PostgreSQL database dump
--

\restrict dGRd4Krgea3U9YewdPSEwo4tNIFvXw4Q7ULf3TNVzOlJUjbc0bMKe8CdGzL1rh3

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoice_order_forms; Type: TABLE; Schema: lh_billing; Owner: -
--

CREATE TABLE lh_billing.invoice_order_forms (
    invoice_order_form_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    ofrm_id bigint NOT NULL,
    source_period_start date NOT NULL,
    source_period_end date NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_invoice_order_forms__period_valid CHECK ((source_period_end >= source_period_start))
);


--
-- Name: TABLE invoice_order_forms; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON TABLE lh_billing.invoice_order_forms IS 'Maps invoices to source order forms (supports consolidated invoices)';


--
-- Name: COLUMN invoice_order_forms.source_period_start; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.invoice_order_forms.source_period_start IS 'Order form contribution start date for this invoice';


--
-- Name: COLUMN invoice_order_forms.source_period_end; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.invoice_order_forms.source_period_end IS 'Order form contribution end date for this invoice';


--
-- Name: invoice_order_forms_invoice_order_form_id_seq; Type: SEQUENCE; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.invoice_order_forms ALTER COLUMN invoice_order_form_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing.invoice_order_forms_invoice_order_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_order_forms invoice_order_forms_pkey; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_order_forms
    ADD CONSTRAINT invoice_order_forms_pkey PRIMARY KEY (invoice_order_form_id);


--
-- Name: invoice_order_forms uq_invoice_order_forms__invoice_id_ofrm_id; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_order_forms
    ADD CONSTRAINT uq_invoice_order_forms__invoice_id_ofrm_id UNIQUE (invoice_id, ofrm_id);


--
-- Name: ix_invoice_order_forms__invoice_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_invoice_order_forms__invoice_id ON lh_billing.invoice_order_forms USING btree (invoice_id);


--
-- Name: ix_invoice_order_forms__ofrm_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_invoice_order_forms__ofrm_id ON lh_billing.invoice_order_forms USING btree (ofrm_id);


--
-- Name: invoice_order_forms trg_update_invoice_order_forms_updated_at; Type: TRIGGER; Schema: lh_billing; Owner: -
--

CREATE TRIGGER trg_update_invoice_order_forms_updated_at BEFORE UPDATE ON lh_billing.invoice_order_forms FOR EACH ROW EXECUTE FUNCTION lh_billing.set_updated_at();


--
-- Name: invoice_order_forms fk_invoice_order_forms__customer_order_forms; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_order_forms
    ADD CONSTRAINT fk_invoice_order_forms__customer_order_forms FOREIGN KEY (ofrm_id) REFERENCES public.customer_order_forms(ofrm_id) ON DELETE RESTRICT;


--
-- Name: invoice_order_forms fk_invoice_order_forms__invoices; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.invoice_order_forms
    ADD CONSTRAINT fk_invoice_order_forms__invoices FOREIGN KEY (invoice_id) REFERENCES lh_billing.invoices(invoice_id) ON DELETE RESTRICT;


--
-- Name: invoice_order_forms; Type: ROW SECURITY; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.invoice_order_forms ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict dGRd4Krgea3U9YewdPSEwo4tNIFvXw4Q7ULf3TNVzOlJUjbc0bMKe8CdGzL1rh3

