--
-- PostgreSQL database dump
--

\restrict d6q55lrN3bDelksZMYHTaQw2wEXfTPnjbVkaRSfWSwl2zDBUA0l1luvEfZJPJzA

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: cash_operations; Type: TABLE; Schema: lh_tims_emulator; Owner: -
--

CREATE TABLE lh_tims_emulator.cash_operations (
    id bigint NOT NULL,
    operation_type smallint NOT NULL,
    amount numeric(19,4) NOT NULL,
    performed_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_cash_operations__amount_non_negative CHECK ((amount >= (0)::numeric)),
    CONSTRAINT ck_cash_operations__operation_type CHECK ((operation_type = ANY (ARRAY[0, 1])))
);


--
-- Name: TABLE cash_operations; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON TABLE lh_tims_emulator.cash_operations IS 'Cash-in (0) and cash-out (1) operations';


--
-- Name: COLUMN cash_operations.operation_type; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.cash_operations.operation_type IS '0=Cash-in, 1=Cash-out';


--
-- Name: COLUMN cash_operations.amount; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.cash_operations.amount IS 'Cash amount for the operation (numeric(19,4)).';


--
-- Name: COLUMN cash_operations.performed_at; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.cash_operations.performed_at IS 'Timestamp when the operation was performed.';


--
-- Name: cash_operations_id_seq; Type: SEQUENCE; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE lh_tims_emulator.cash_operations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_tims_emulator.cash_operations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cash_operations cash_operations_pkey; Type: CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.cash_operations
    ADD CONSTRAINT cash_operations_pkey PRIMARY KEY (id);


--
-- Name: ix_cash_operations__performed_at; Type: INDEX; Schema: lh_tims_emulator; Owner: -
--

CREATE INDEX ix_cash_operations__performed_at ON lh_tims_emulator.cash_operations USING btree (performed_at);


--
-- Name: cash_operations trg_update_cash_operations_updated_at; Type: TRIGGER; Schema: lh_tims_emulator; Owner: -
--

CREATE TRIGGER trg_update_cash_operations_updated_at BEFORE UPDATE ON lh_tims_emulator.cash_operations FOR EACH ROW EXECUTE FUNCTION lh_tims_emulator.update_updated_at_column();


--
-- PostgreSQL database dump complete
--

\unrestrict d6q55lrN3bDelksZMYHTaQw2wEXfTPnjbVkaRSfWSwl2zDBUA0l1luvEfZJPJzA

