--
-- PostgreSQL database dump
--

\restrict fPfexDHLOZyoZmjyfP3PGMfyJXIrR5Ofijd0s7NKGMe3Tk9ai9JmMP5Tfe9EpR7

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: configuration; Type: TABLE; Schema: lh_billing; Owner: -
--

CREATE TABLE lh_billing.configuration (
    configuration_id bigint NOT NULL,
    cfg_key text NOT NULL,
    cfg_value text NOT NULL,
    cfg_description text,
    cmp_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_configuration__cfg_key_not_blank CHECK ((btrim(cfg_key) <> ''::text)),
    CONSTRAINT ck_configuration__cfg_value_not_blank CHECK ((btrim(cfg_value) <> ''::text))
);


--
-- Name: TABLE configuration; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON TABLE lh_billing.configuration IS 'Billing-specific configuration settings (scoped by company or global)';


--
-- Name: COLUMN configuration.cfg_key; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.configuration.cfg_key IS 'Configuration key (e.g., InvoiceSenderEmail, AlertRecipients)';


--
-- Name: COLUMN configuration.cfg_value; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.configuration.cfg_value IS 'Configuration value as text';


--
-- Name: COLUMN configuration.cmp_id; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.configuration.cmp_id IS 'Optional company scope (NULL = global default)';


--
-- Name: configuration_configuration_id_seq; Type: SEQUENCE; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.configuration ALTER COLUMN configuration_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing.configuration_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuration configuration_pkey; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.configuration
    ADD CONSTRAINT configuration_pkey PRIMARY KEY (configuration_id);


--
-- Name: configuration uq_configuration__cfg_key_cmp_id; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.configuration
    ADD CONSTRAINT uq_configuration__cfg_key_cmp_id UNIQUE (cfg_key, cmp_id);


--
-- Name: ix_configuration__cfg_key; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_configuration__cfg_key ON lh_billing.configuration USING btree (cfg_key);


--
-- Name: ix_configuration__cmp_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_configuration__cmp_id ON lh_billing.configuration USING btree (cmp_id);


--
-- Name: uq_configuration__cfg_key_global; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE UNIQUE INDEX uq_configuration__cfg_key_global ON lh_billing.configuration USING btree (cfg_key) WHERE (cmp_id IS NULL);


--
-- Name: configuration trg_update_configuration_updated_at; Type: TRIGGER; Schema: lh_billing; Owner: -
--

CREATE TRIGGER trg_update_configuration_updated_at BEFORE UPDATE ON lh_billing.configuration FOR EACH ROW EXECUTE FUNCTION lh_billing.set_updated_at();


--
-- Name: configuration fk_configuration__companies; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.configuration
    ADD CONSTRAINT fk_configuration__companies FOREIGN KEY (cmp_id) REFERENCES public.companies(cmp_id) ON DELETE RESTRICT;


--
-- Name: configuration; Type: ROW SECURITY; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.configuration ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict fPfexDHLOZyoZmjyfP3PGMfyJXIrR5Ofijd0s7NKGMe3Tk9ai9JmMP5Tfe9EpR7

