--
-- PostgreSQL database dump
--

\restrict EZg7dKdnR0tlkHcKCKBgBNPZDpSuF5oakRJBrvR0jhbymBcVUXDcF9WhJMeArPK

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: payment_methods; Type: TABLE; Schema: lh_tims_emulator; Owner: -
--

CREATE TABLE lh_tims_emulator.payment_methods (
    id bigint NOT NULL,
    method_index smallint NOT NULL,
    pay_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_payment_methods__method_index_range CHECK (((method_index >= 0) AND (method_index <= 5))),
    CONSTRAINT ck_payment_methods__pay_name_length CHECK (((char_length(pay_name) >= 1) AND (char_length(pay_name) <= 16))),
    CONSTRAINT ck_payment_methods__pay_name_not_blank CHECK ((btrim(pay_name) <> ''::text))
);


--
-- Name: TABLE payment_methods; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON TABLE lh_tims_emulator.payment_methods IS 'Configurable payment method names (index 0=CASH is immutable)';


--
-- Name: COLUMN payment_methods.method_index; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.payment_methods.method_index IS 'Payment method index (0..5).';


--
-- Name: COLUMN payment_methods.pay_name; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.payment_methods.pay_name IS 'Payment method display name (1..16 chars).';


--
-- Name: payment_methods_id_seq; Type: SEQUENCE; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE lh_tims_emulator.payment_methods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_tims_emulator.payment_methods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_methods payment_methods_method_index_key; Type: CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.payment_methods
    ADD CONSTRAINT payment_methods_method_index_key UNIQUE (method_index);


--
-- Name: payment_methods payment_methods_pkey; Type: CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.payment_methods
    ADD CONSTRAINT payment_methods_pkey PRIMARY KEY (id);


--
-- Name: payment_methods trg_update_payment_methods_updated_at; Type: TRIGGER; Schema: lh_tims_emulator; Owner: -
--

CREATE TRIGGER trg_update_payment_methods_updated_at BEFORE UPDATE ON lh_tims_emulator.payment_methods FOR EACH ROW EXECUTE FUNCTION lh_tims_emulator.update_updated_at_column();


--
-- PostgreSQL database dump complete
--

\unrestrict EZg7dKdnR0tlkHcKCKBgBNPZDpSuF5oakRJBrvR0jhbymBcVUXDcF9WhJMeArPK

