--
-- PostgreSQL database dump
--

\restrict DOZlBXOljv6MKIM4t9iLG206oNMeTCex6UwDxif4hSqggIvEwuQ9jyCL0OPkxA8

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: tax_rates; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.tax_rates (
    tax_rate_id bigint NOT NULL,
    country_code character(2) NOT NULL,
    tax_type text NOT NULL,
    service_category text,
    rate numeric(5,4) NOT NULL,
    is_inclusive boolean DEFAULT false NOT NULL,
    effective_date date NOT NULL,
    end_date date,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_tax_rates__country_code_not_blank CHECK ((btrim((country_code)::text) <> ''::text)),
    CONSTRAINT ck_tax_rates__date_range_valid CHECK (((end_date IS NULL) OR (end_date >= effective_date))),
    CONSTRAINT ck_tax_rates__rate_non_negative CHECK ((rate >= (0)::numeric)),
    CONSTRAINT ck_tax_rates__tax_type_not_blank CHECK ((btrim(tax_type) <> ''::text))
);


--
-- Name: TABLE tax_rates; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.tax_rates IS 'Tax rate configuration by country, type, and effective date';


--
-- Name: COLUMN tax_rates.country_code; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.tax_rates.country_code IS 'ISO 3166-1 alpha-2 country code';


--
-- Name: COLUMN tax_rates.tax_type; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.tax_rates.tax_type IS 'Tax type: VAT, GST, WHT, etc.';


--
-- Name: COLUMN tax_rates.rate; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.tax_rates.rate IS 'Tax rate as decimal (e.g., 0.16 for 16%)';


--
-- Name: tax_rates_tax_rate_id_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.tax_rates ALTER COLUMN tax_rate_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.tax_rates_tax_rate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tax_rates tax_rates_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.tax_rates
    ADD CONSTRAINT tax_rates_pkey PRIMARY KEY (tax_rate_id);


--
-- Name: tax_rates uq_tax_rates__country_type_category_date; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.tax_rates
    ADD CONSTRAINT uq_tax_rates__country_type_category_date UNIQUE (country_code, tax_type, service_category, effective_date);


--
-- Name: ix_tax_rates__lookup; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_tax_rates__lookup ON lh_billing_agile.tax_rates USING btree (country_code, tax_type, effective_date);


--
-- Name: uq_tax_rates__country_type_date_no_category; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE UNIQUE INDEX uq_tax_rates__country_type_date_no_category ON lh_billing_agile.tax_rates USING btree (country_code, tax_type, effective_date) WHERE (service_category IS NULL);


--
-- Name: tax_rates trg_update_tax_rates_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_tax_rates_updated_at BEFORE UPDATE ON lh_billing_agile.tax_rates FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: tax_rates; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.tax_rates ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict DOZlBXOljv6MKIM4t9iLG206oNMeTCex6UwDxif4hSqggIvEwuQ9jyCL0OPkxA8

