--
-- PostgreSQL database dump
--

\restrict gf5yZq5AFORGjWK30t7bgRAJk1WoDRdwBE5j23lYWNOTT7WKrqOyEflIDcmriQk

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoice_pdf_artifacts; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.invoice_pdf_artifacts (
    invoice_pdf_artifact_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    original_pdf_blob_path text NOT NULL,
    original_pdf_sha256 text NOT NULL,
    postprocessed_pdf_blob_path text,
    postprocessed_pdf_sha256 text,
    stamp_rule_id text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_invoice_pdf_artifacts__original_pdf_blob_path_not_blank CHECK ((btrim(original_pdf_blob_path) <> ''::text)),
    CONSTRAINT ck_invoice_pdf_artifacts__original_pdf_sha256_not_blank CHECK ((btrim(original_pdf_sha256) <> ''::text)),
    CONSTRAINT ck_invoice_pdf_artifacts__postprocessed_pdf_blob_path_not_blank CHECK (((postprocessed_pdf_blob_path IS NULL) OR (btrim(postprocessed_pdf_blob_path) <> ''::text))),
    CONSTRAINT ck_invoice_pdf_artifacts__postprocessed_pdf_consistent CHECK (((postprocessed_pdf_blob_path IS NULL) = (postprocessed_pdf_sha256 IS NULL))),
    CONSTRAINT ck_invoice_pdf_artifacts__postprocessed_pdf_sha256_not_blank CHECK (((postprocessed_pdf_sha256 IS NULL) OR (btrim(postprocessed_pdf_sha256) <> ''::text))),
    CONSTRAINT ck_invoice_pdf_artifacts__postprocessed_requires_stamp_rule_id CHECK ((((postprocessed_pdf_blob_path IS NULL) AND (postprocessed_pdf_sha256 IS NULL)) OR (stamp_rule_id IS NOT NULL))),
    CONSTRAINT ck_invoice_pdf_artifacts__stamp_requires_postprocessed_pdf CHECK (((stamp_rule_id IS NULL) OR ((postprocessed_pdf_blob_path IS NOT NULL) AND (postprocessed_pdf_sha256 IS NOT NULL)))),
    CONSTRAINT ck_invoice_pdf_artifacts__stamp_rule_id_not_blank CHECK (((stamp_rule_id IS NULL) OR (btrim(stamp_rule_id) <> ''::text)))
);


--
-- Name: TABLE invoice_pdf_artifacts; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.invoice_pdf_artifacts IS 'Per-invoice evidence of original and postprocessed PDFs (paths + sha256 hashes).';


--
-- Name: invoice_pdf_artifacts_invoice_pdf_artifact_id_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_pdf_artifacts ALTER COLUMN invoice_pdf_artifact_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.invoice_pdf_artifacts_invoice_pdf_artifact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_pdf_artifacts invoice_pdf_artifacts_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_pdf_artifacts
    ADD CONSTRAINT invoice_pdf_artifacts_pkey PRIMARY KEY (invoice_pdf_artifact_id);


--
-- Name: invoice_pdf_artifacts uq_invoice_pdf_artifacts__invoice_id; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_pdf_artifacts
    ADD CONSTRAINT uq_invoice_pdf_artifacts__invoice_id UNIQUE (invoice_id);


--
-- Name: invoice_pdf_artifacts trg_update_invoice_pdf_artifacts_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_invoice_pdf_artifacts_updated_at BEFORE UPDATE ON lh_billing_agile.invoice_pdf_artifacts FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: invoice_pdf_artifacts fk_invoice_pdf_artifacts__invoices; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_pdf_artifacts
    ADD CONSTRAINT fk_invoice_pdf_artifacts__invoices FOREIGN KEY (invoice_id) REFERENCES lh_billing_agile.invoices(invoice_id) ON DELETE RESTRICT;


--
-- Name: invoice_pdf_artifacts; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_pdf_artifacts ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict gf5yZq5AFORGjWK30t7bgRAJk1WoDRdwBE5j23lYWNOTT7WKrqOyEflIDcmriQk

