--
-- PostgreSQL database dump
--

\restrict dFbPY0ssCuTrHZG53KfH01zNag8lbYLnaXBlKbMEpp3Yt34G1nuCQ5d4egbu8MN

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: device_state; Type: TABLE; Schema: lh_tims_emulator; Owner: -
--

CREATE TABLE lh_tims_emulator.device_state (
    id bigint NOT NULL,
    state_key text NOT NULL,
    state_value jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_device_state__state_key_not_blank CHECK ((btrim(state_key) <> ''::text))
);


--
-- Name: TABLE device_state; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON TABLE lh_tims_emulator.device_state IS 'Stores device state (PIN status, settings).';


--
-- Name: COLUMN device_state.state_key; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.device_state.state_key IS 'State identifier (e.g., pin_required, auto_print).';


--
-- Name: COLUMN device_state.state_value; Type: COMMENT; Schema: lh_tims_emulator; Owner: -
--

COMMENT ON COLUMN lh_tims_emulator.device_state.state_value IS 'JSON value for the state.';


--
-- Name: device_state_id_seq; Type: SEQUENCE; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE lh_tims_emulator.device_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_tims_emulator.device_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device_state device_state_pkey; Type: CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.device_state
    ADD CONSTRAINT device_state_pkey PRIMARY KEY (id);


--
-- Name: device_state device_state_state_key_key; Type: CONSTRAINT; Schema: lh_tims_emulator; Owner: -
--

ALTER TABLE ONLY lh_tims_emulator.device_state
    ADD CONSTRAINT device_state_state_key_key UNIQUE (state_key);


--
-- Name: device_state trg_update_device_state_updated_at; Type: TRIGGER; Schema: lh_tims_emulator; Owner: -
--

CREATE TRIGGER trg_update_device_state_updated_at BEFORE UPDATE ON lh_tims_emulator.device_state FOR EACH ROW EXECUTE FUNCTION lh_tims_emulator.update_updated_at_column();


--
-- PostgreSQL database dump complete
--

\unrestrict dFbPY0ssCuTrHZG53KfH01zNag8lbYLnaXBlKbMEpp3Yt34G1nuCQ5d4egbu8MN

