--
-- PostgreSQL database dump
--

\restrict BH5iZpLzkZXvUzEk8mPQr3Zbch6O1aCwQE4URXhQXmb4ER4anymePkAidaZgNAr

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: billing_schedules; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.billing_schedules (
    billing_schedule_id bigint NOT NULL,
    scope_type text NOT NULL,
    cmp_id bigint,
    cctr_id bigint,
    ofrm_id bigint,
    frequency text DEFAULT 'quarterly'::text NOT NULL,
    timing text DEFAULT 'in_advance'::text NOT NULL,
    issue_days_before integer DEFAULT 45 NOT NULL,
    period_alignment text DEFAULT 'calendar_quarter'::text NOT NULL,
    anchor_date date,
    preferred_invoice_grouping text DEFAULT 'per_company'::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_billing_schedules__anchor_date_required_when_alignment_is_an CHECK (((period_alignment <> 'anchor_date'::text) OR (anchor_date IS NOT NULL))),
    CONSTRAINT ck_billing_schedules__calendar_alignment_matches_frequency CHECK (((period_alignment <> ALL (ARRAY['calendar_month'::text, 'calendar_quarter'::text, 'calendar_half_year'::text, 'calendar_year'::text])) OR (((frequency = 'monthly'::text) AND (period_alignment = 'calendar_month'::text)) OR ((frequency = 'quarterly'::text) AND (period_alignment = 'calendar_quarter'::text)) OR ((frequency = 'semi-annual'::text) AND (period_alignment = 'calendar_half_year'::text)) OR ((frequency = 'annual'::text) AND (period_alignment = 'calendar_year'::text))))),
    CONSTRAINT ck_billing_schedules__frequency CHECK ((frequency = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'semi-annual'::text, 'annual'::text]))),
    CONSTRAINT ck_billing_schedules__issue_days_before_positive CHECK ((issue_days_before > 0)),
    CONSTRAINT ck_billing_schedules__period_alignment CHECK ((period_alignment = ANY (ARRAY['calendar_month'::text, 'calendar_quarter'::text, 'calendar_half_year'::text, 'calendar_year'::text, 'contract_anniversary'::text, 'anchor_date'::text]))),
    CONSTRAINT ck_billing_schedules__preferred_invoice_grouping CHECK ((preferred_invoice_grouping = ANY (ARRAY['per_order_form'::text, 'per_company'::text]))),
    CONSTRAINT ck_billing_schedules__scope CHECK ((((scope_type = 'company'::text) AND (cmp_id IS NOT NULL) AND (cctr_id IS NULL) AND (ofrm_id IS NULL)) OR ((scope_type = 'contract'::text) AND (cctr_id IS NOT NULL) AND (cmp_id IS NULL) AND (ofrm_id IS NULL)) OR ((scope_type = 'order_form'::text) AND (ofrm_id IS NOT NULL) AND (cmp_id IS NULL) AND (cctr_id IS NULL)))),
    CONSTRAINT ck_billing_schedules__scope_type CHECK ((scope_type = ANY (ARRAY['company'::text, 'contract'::text, 'order_form'::text]))),
    CONSTRAINT ck_billing_schedules__timing CHECK ((timing = ANY (ARRAY['in_advance'::text, 'in_arrears'::text])))
);


--
-- Name: TABLE billing_schedules; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.billing_schedules IS 'Billing schedule configuration scoped to company, contract, or order form';


--
-- Name: COLUMN billing_schedules.scope_type; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.billing_schedules.scope_type IS 'Scope level: company, contract, or order_form';


--
-- Name: COLUMN billing_schedules.frequency; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.billing_schedules.frequency IS 'Billing frequency: monthly, quarterly, semi-annual, annual';


--
-- Name: COLUMN billing_schedules.anchor_date; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.billing_schedules.anchor_date IS 'Required when period_alignment = anchor_date; defines the anchor used to compute anchored periods';


--
-- Name: COLUMN billing_schedules.preferred_invoice_grouping; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON COLUMN lh_billing_agile.billing_schedules.preferred_invoice_grouping IS 'Invoice grouping preference: per_order_form or per_company';


--
-- Name: billing_schedules_billing_schedule_id_seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.billing_schedules ALTER COLUMN billing_schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.billing_schedules_billing_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: billing_schedules billing_schedules_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.billing_schedules
    ADD CONSTRAINT billing_schedules_pkey PRIMARY KEY (billing_schedule_id);


--
-- Name: uq_billing_schedules__cctr_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE UNIQUE INDEX uq_billing_schedules__cctr_id ON lh_billing_agile.billing_schedules USING btree (cctr_id) WHERE (scope_type = 'contract'::text);


--
-- Name: uq_billing_schedules__cmp_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE UNIQUE INDEX uq_billing_schedules__cmp_id ON lh_billing_agile.billing_schedules USING btree (cmp_id) WHERE (scope_type = 'company'::text);


--
-- Name: uq_billing_schedules__ofrm_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE UNIQUE INDEX uq_billing_schedules__ofrm_id ON lh_billing_agile.billing_schedules USING btree (ofrm_id) WHERE (scope_type = 'order_form'::text);


--
-- Name: billing_schedules trg_update_billing_schedules_updated_at; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_update_billing_schedules_updated_at BEFORE UPDATE ON lh_billing_agile.billing_schedules FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.set_updated_at();


--
-- Name: billing_schedules fk_billing_schedules__companies; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.billing_schedules
    ADD CONSTRAINT fk_billing_schedules__companies FOREIGN KEY (cmp_id) REFERENCES public.companies(cmp_id) ON DELETE RESTRICT;


--
-- Name: billing_schedules fk_billing_schedules__customer_contracts; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.billing_schedules
    ADD CONSTRAINT fk_billing_schedules__customer_contracts FOREIGN KEY (cctr_id) REFERENCES public.customer_contracts(cctr_id) ON DELETE RESTRICT;


--
-- Name: billing_schedules fk_billing_schedules__customer_order_forms; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.billing_schedules
    ADD CONSTRAINT fk_billing_schedules__customer_order_forms FOREIGN KEY (ofrm_id) REFERENCES public.customer_order_forms(ofrm_id) ON DELETE RESTRICT;


--
-- Name: billing_schedules; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.billing_schedules ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict BH5iZpLzkZXvUzEk8mPQr3Zbch6O1aCwQE4URXhQXmb4ER4anymePkAidaZgNAr

