--
-- PostgreSQL database dump
--

\restrict 8rOj2uyjQOBwEXUUy5S0KvRCsYBayT9BgZWudYBaouOporECpgV3wjkpvfJyAb8

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: order_form_charges; Type: TABLE; Schema: lh_billing; Owner: -
--

CREATE TABLE lh_billing.order_form_charges (
    order_form_charge_id bigint NOT NULL,
    ofrm_id bigint NOT NULL,
    odrl_id bigint,
    charge_type_code text NOT NULL,
    charge_code text NOT NULL,
    charge_description text NOT NULL,
    currency character(3) NOT NULL,
    unit_code text NOT NULL,
    unit_fee numeric(15,2) NOT NULL,
    discount_percent numeric(5,2) DEFAULT 0 NOT NULL,
    is_recurring boolean DEFAULT false NOT NULL,
    one_off_date date,
    effective_start date NOT NULL,
    effective_end date,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_order_form_charges__charge_code_not_blank CHECK ((btrim(charge_code) <> ''::text)),
    CONSTRAINT ck_order_form_charges__charge_description_not_blank CHECK ((btrim(charge_description) <> ''::text)),
    CONSTRAINT ck_order_form_charges__currency_not_blank CHECK ((btrim((currency)::text) <> ''::text)),
    CONSTRAINT ck_order_form_charges__discount_percent_valid CHECK (((discount_percent >= (0)::numeric) AND (discount_percent <= (100)::numeric))),
    CONSTRAINT ck_order_form_charges__effective_window_valid CHECK (((effective_end IS NULL) OR (effective_end >= effective_start))),
    CONSTRAINT ck_order_form_charges__one_off_date_required CHECK ((((is_recurring = true) AND (one_off_date IS NULL)) OR ((is_recurring = false) AND (one_off_date IS NOT NULL)))),
    CONSTRAINT ck_order_form_charges__unit_fee_non_negative CHECK ((unit_fee >= (0)::numeric))
);


--
-- Name: TABLE order_form_charges; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON TABLE lh_billing.order_form_charges IS 'Add-on charges (goods/expenses), one-off or recurring, optionally linked to an ordered role';


--
-- Name: COLUMN order_form_charges.odrl_id; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.order_form_charges.odrl_id IS 'Optional: the ordered role this charge is for (e.g., laptop for Senior Dev slot). NULL means order-form-wide (e.g., shared office). At invoice time, we look up the current holder.';


--
-- Name: COLUMN order_form_charges.charge_code; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.order_form_charges.charge_code IS 'Stable identifier for this charge within the order form (e.g., LAPTOP-SENIORDEV-2025, OFFICE-SHARED)';


--
-- Name: COLUMN order_form_charges.is_recurring; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.order_form_charges.is_recurring IS 'True if this charge should be applied in each invoiced period overlapping the effective window';


--
-- Name: COLUMN order_form_charges.one_off_date; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.order_form_charges.one_off_date IS 'Required when is_recurring is false; used to include the charge on invoices covering that date';


--
-- Name: order_form_charges_order_form_charge_id_seq; Type: SEQUENCE; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.order_form_charges ALTER COLUMN order_form_charge_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing.order_form_charges_order_form_charge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_form_charges order_form_charges_pkey; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.order_form_charges
    ADD CONSTRAINT order_form_charges_pkey PRIMARY KEY (order_form_charge_id);


--
-- Name: order_form_charges uq_order_form_charges__ofrm_id_charge_code; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.order_form_charges
    ADD CONSTRAINT uq_order_form_charges__ofrm_id_charge_code UNIQUE (ofrm_id, charge_code);


--
-- Name: ix_order_form_charges__active; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_order_form_charges__active ON lh_billing.order_form_charges USING btree (is_active) WHERE (is_active = true);


--
-- Name: ix_order_form_charges__odrl_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_order_form_charges__odrl_id ON lh_billing.order_form_charges USING btree (odrl_id) WHERE (odrl_id IS NOT NULL);


--
-- Name: ix_order_form_charges__ofrm_id; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_order_form_charges__ofrm_id ON lh_billing.order_form_charges USING btree (ofrm_id);


--
-- Name: ix_order_form_charges__type; Type: INDEX; Schema: lh_billing; Owner: -
--

CREATE INDEX ix_order_form_charges__type ON lh_billing.order_form_charges USING btree (charge_type_code);


--
-- Name: order_form_charges trg_update_order_form_charges_updated_at; Type: TRIGGER; Schema: lh_billing; Owner: -
--

CREATE TRIGGER trg_update_order_form_charges_updated_at BEFORE UPDATE ON lh_billing.order_form_charges FOR EACH ROW EXECUTE FUNCTION lh_billing.set_updated_at();


--
-- Name: order_form_charges fk_order_form_charges__billing_units; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.order_form_charges
    ADD CONSTRAINT fk_order_form_charges__billing_units FOREIGN KEY (unit_code) REFERENCES lh_billing.billing_units(unit_code) ON DELETE RESTRICT;


--
-- Name: order_form_charges fk_order_form_charges__charge_types; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.order_form_charges
    ADD CONSTRAINT fk_order_form_charges__charge_types FOREIGN KEY (charge_type_code) REFERENCES lh_billing.charge_types(charge_type_code) ON DELETE RESTRICT;


--
-- Name: order_form_charges fk_order_form_charges__customer_order_forms; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.order_form_charges
    ADD CONSTRAINT fk_order_form_charges__customer_order_forms FOREIGN KEY (ofrm_id) REFERENCES public.customer_order_forms(ofrm_id) ON DELETE RESTRICT;


--
-- Name: order_form_charges fk_order_form_charges__orderform_ordered_roles; Type: FK CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.order_form_charges
    ADD CONSTRAINT fk_order_form_charges__orderform_ordered_roles FOREIGN KEY (odrl_id) REFERENCES public.orderform_ordered_roles(odrl_id) ON DELETE RESTRICT;


--
-- Name: order_form_charges; Type: ROW SECURITY; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.order_form_charges ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict 8rOj2uyjQOBwEXUUy5S0KvRCsYBayT9BgZWudYBaouOporECpgV3wjkpvfJyAb8

