--
-- PostgreSQL database dump
--

\restrict n72QowIzYlsUNq3a3erZja8yASsCW8SOmGeT1Z22EFrqZ5M3aUh4qZp4IeSN407

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: charge_types; Type: TABLE; Schema: lh_billing; Owner: -
--

CREATE TABLE lh_billing.charge_types (
    charge_type_id bigint NOT NULL,
    charge_type_code text NOT NULL,
    charge_type_description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_charge_types__charge_type_code_not_blank CHECK ((btrim(charge_type_code) <> ''::text))
);


--
-- Name: TABLE charge_types; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON TABLE lh_billing.charge_types IS 'Allowed charge types for add-ons (good, expense, etc.). Lookup table to allow extending without schema changes.';


--
-- Name: COLUMN charge_types.charge_type_code; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.charge_types.charge_type_code IS 'Short code used in FKs (e.g., good, expense)';


--
-- Name: COLUMN charge_types.charge_type_description; Type: COMMENT; Schema: lh_billing; Owner: -
--

COMMENT ON COLUMN lh_billing.charge_types.charge_type_description IS 'Human-readable description for UI display (e.g., "Equipment/Goods", "Travel & Expenses")';


--
-- Name: charge_types_charge_type_id_seq; Type: SEQUENCE; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.charge_types ALTER COLUMN charge_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing.charge_types_charge_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: charge_types charge_types_pkey; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.charge_types
    ADD CONSTRAINT charge_types_pkey PRIMARY KEY (charge_type_id);


--
-- Name: charge_types uq_charge_types__charge_type_code; Type: CONSTRAINT; Schema: lh_billing; Owner: -
--

ALTER TABLE ONLY lh_billing.charge_types
    ADD CONSTRAINT uq_charge_types__charge_type_code UNIQUE (charge_type_code);


--
-- Name: charge_types trg_update_charge_types_updated_at; Type: TRIGGER; Schema: lh_billing; Owner: -
--

CREATE TRIGGER trg_update_charge_types_updated_at BEFORE UPDATE ON lh_billing.charge_types FOR EACH ROW EXECUTE FUNCTION lh_billing.set_updated_at();


--
-- Name: charge_types; Type: ROW SECURITY; Schema: lh_billing; Owner: -
--

ALTER TABLE lh_billing.charge_types ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict n72QowIzYlsUNq3a3erZja8yASsCW8SOmGeT1Z22EFrqZ5M3aUh4qZp4IeSN407

