--
-- PostgreSQL database dump
--

\restrict fGYiJaGtSZtEbPoPmXZ1t4rZKMahAVmxY2RwjrvPz8Mkp2S7dVc9X5jcesWIQgQ

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.8 (Ubuntu 17.8-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: invoice_postprocessing_events; Type: TABLE; Schema: lh_billing_agile; Owner: -
--

CREATE TABLE lh_billing_agile.invoice_postprocessing_events (
    invoice_postprocessing_event_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    pipeline_version_id bigint,
    step_key text NOT NULL,
    outcome text NOT NULL,
    message text,
    correlation_id text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_invoice_postprocessing_events__correlation_id_not_blank CHECK ((btrim(correlation_id) <> ''::text)),
    CONSTRAINT ck_invoice_postprocessing_events__message_bounded CHECK (((message IS NULL) OR (char_length(message) <= 4000))),
    CONSTRAINT ck_invoice_postprocessing_events__message_not_blank CHECK (((message IS NULL) OR (btrim(message) <> ''::text))),
    CONSTRAINT ck_invoice_postprocessing_events__outcome CHECK ((outcome = ANY (ARRAY['succeeded'::text, 'transient_failed'::text, 'permanent_failed'::text]))),
    CONSTRAINT ck_invoice_postprocessing_events__step_key_not_blank CHECK ((btrim(step_key) <> ''::text))
);


--
-- Name: TABLE invoice_postprocessing_events; Type: COMMENT; Schema: lh_billing_agile; Owner: -
--

COMMENT ON TABLE lh_billing_agile.invoice_postprocessing_events IS 'Append-only audit trail of Phase 3 pipeline activity (per step outcomes).';


--
-- Name: invoice_postprocessing_events_invoice_postprocessing_event__seq; Type: SEQUENCE; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_postprocessing_events ALTER COLUMN invoice_postprocessing_event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lh_billing_agile.invoice_postprocessing_events_invoice_postprocessing_event__seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_postprocessing_events invoice_postprocessing_events_pkey; Type: CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_postprocessing_events
    ADD CONSTRAINT invoice_postprocessing_events_pkey PRIMARY KEY (invoice_postprocessing_event_id);


--
-- Name: ix_invoice_postprocessing_events__correlation_id; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoice_postprocessing_events__correlation_id ON lh_billing_agile.invoice_postprocessing_events USING btree (correlation_id);


--
-- Name: ix_invoice_postprocessing_events__invoice_id_created_at; Type: INDEX; Schema: lh_billing_agile; Owner: -
--

CREATE INDEX ix_invoice_postprocessing_events__invoice_id_created_at ON lh_billing_agile.invoice_postprocessing_events USING btree (invoice_id, created_at);


--
-- Name: invoice_postprocessing_events trg_reject_invoice_postprocessing_events_mutation; Type: TRIGGER; Schema: lh_billing_agile; Owner: -
--

CREATE TRIGGER trg_reject_invoice_postprocessing_events_mutation BEFORE DELETE OR UPDATE ON lh_billing_agile.invoice_postprocessing_events FOR EACH ROW EXECUTE FUNCTION lh_billing_agile.reject_invoice_postprocessing_events_mutation();


--
-- Name: invoice_postprocessing_events fk_invoice_postprocessing_events__invoices; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_postprocessing_events
    ADD CONSTRAINT fk_invoice_postprocessing_events__invoices FOREIGN KEY (invoice_id) REFERENCES lh_billing_agile.invoices(invoice_id) ON DELETE RESTRICT;


--
-- Name: invoice_postprocessing_events fk_invoice_postprocessing_events__postprocessing_pipeline_versi; Type: FK CONSTRAINT; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE ONLY lh_billing_agile.invoice_postprocessing_events
    ADD CONSTRAINT fk_invoice_postprocessing_events__postprocessing_pipeline_versi FOREIGN KEY (pipeline_version_id) REFERENCES lh_billing_agile.postprocessing_pipeline_versions(postprocessing_pipeline_version_id) ON DELETE RESTRICT;


--
-- Name: invoice_postprocessing_events; Type: ROW SECURITY; Schema: lh_billing_agile; Owner: -
--

ALTER TABLE lh_billing_agile.invoice_postprocessing_events ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict fGYiJaGtSZtEbPoPmXZ1t4rZKMahAVmxY2RwjrvPz8Mkp2S7dVc9X5jcesWIQgQ

