--
-- PostgreSQL database dump
--

\restrict fPVxBJmgfOhyBK2H2bxdrrj67lRYCH0KNzQBJHhoowZGB4TN6sFOdnegcMSYjRj

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: contract_alternate_contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contract_alternate_contacts (
    cctraltct_id bigint NOT NULL,
    cctr_id bigint NOT NULL,
    cctraltct_first_name text,
    cctraltct_middle_name text,
    cctraltct_last_name text,
    cctraltct_contact_description text,
    cctraltct_role text NOT NULL,
    cctraltct_contact_type text NOT NULL,
    cctraltct_work_email character varying(320) NOT NULL,
    cctraltct_mobile_number text,
    cctraltct_postal_address text,
    cctraltct_street_address_line1 text,
    cctraltct_street_address_line2 text,
    cctraltct_city text,
    cctraltct_state text,
    cctraltct_postal_code text,
    cctraltct_country text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_contract_alternate_contacts__contact_type CHECK ((cctraltct_contact_type = ANY (ARRAY['Primary'::text, 'Cc'::text, 'Bcc'::text]))),
    CONSTRAINT ck_contract_alternate_contacts__mobile_number_e164 CHECK (((cctraltct_mobile_number IS NULL) OR (cctraltct_mobile_number ~ '^\+[1-9][0-9]{1,14}$'::text))),
    CONSTRAINT ck_contract_alternate_contacts__role_not_blank CHECK ((btrim(cctraltct_role) <> ''::text)),
    CONSTRAINT ck_contract_alternate_contacts__work_email_format CHECK (((cctraltct_work_email)::text ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'::text)),
    CONSTRAINT ck_contract_alternate_contacts__work_email_not_blank CHECK ((btrim((cctraltct_work_email)::text) <> ''::text))
);


--
-- Name: TABLE contract_alternate_contacts; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.contract_alternate_contacts IS 'Alternate contacts for contracts, supporting role-based contact resolution (e.g., BillingContact, DataProtectionContact). Aligns with orderform_alternate_contacts column/contact_type semantics.';


--
-- Name: COLUMN contract_alternate_contacts.cctraltct_role; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.contract_alternate_contacts.cctraltct_role IS 'Role identifier (e.g., BillingContact, PayProofApprover, DataProtectionContact)';


--
-- Name: COLUMN contract_alternate_contacts.cctraltct_contact_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.contract_alternate_contacts.cctraltct_contact_type IS 'Contact type: Primary (To recipient), Cc, or Bcc';


--
-- Name: COLUMN contract_alternate_contacts.cctraltct_work_email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.contract_alternate_contacts.cctraltct_work_email IS 'Work email address (RFC 5321 max length)';


--
-- Name: contract_alternate_contacts_cctraltct_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contract_alternate_contacts ALTER COLUMN cctraltct_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_alternate_contacts_cctraltct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contract_alternate_contacts contract_alternate_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract_alternate_contacts
    ADD CONSTRAINT contract_alternate_contacts_pkey PRIMARY KEY (cctraltct_id);


--
-- Name: ix_contract_alternate_contacts__cctr_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contract_alternate_contacts__cctr_id ON public.contract_alternate_contacts USING btree (cctr_id);


--
-- Name: ix_contract_alternate_contacts__role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contract_alternate_contacts__role ON public.contract_alternate_contacts USING btree (cctraltct_role);


--
-- Name: contract_alternate_contacts trg_update_contract_alternate_contacts_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_update_contract_alternate_contacts_updated_at BEFORE UPDATE ON public.contract_alternate_contacts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: contract_alternate_contacts fk_contract_alternate_contacts__customer_contracts; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract_alternate_contacts
    ADD CONSTRAINT fk_contract_alternate_contacts__customer_contracts FOREIGN KEY (cctr_id) REFERENCES public.customer_contracts(cctr_id) ON DELETE RESTRICT;


--
-- Name: contract_alternate_contacts; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.contract_alternate_contacts ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict fPVxBJmgfOhyBK2H2bxdrrj67lRYCH0KNzQBJHhoowZGB4TN6sFOdnegcMSYjRj

