--
-- PostgreSQL database dump
--

\restrict HobvfKJyb9BJbLU2m1U6kF8irNLMlrrbR3DH7fSLdgk0iAB4TDTtNOGvGGzgwHe

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: company_alternate_contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_alternate_contacts (
    cmpaltct_id bigint NOT NULL,
    cmp_id bigint NOT NULL,
    cmpaltct_first_name text,
    cmpaltct_middle_name text,
    cmpaltct_last_name text,
    cmpaltct_contact_description text,
    cmpaltct_role text NOT NULL,
    cmpaltct_contact_type text NOT NULL,
    cmpaltct_work_email character varying(320) NOT NULL,
    cmpaltct_mobile_number text,
    cmpaltct_postal_address text,
    cmpaltct_street_address_line1 text,
    cmpaltct_street_address_line2 text,
    cmpaltct_city text,
    cmpaltct_state text,
    cmpaltct_postal_code text,
    cmpaltct_country text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_company_alternate_contacts__contact_type CHECK ((cmpaltct_contact_type = ANY (ARRAY['Primary'::text, 'Cc'::text, 'Bcc'::text]))),
    CONSTRAINT ck_company_alternate_contacts__mobile_number_e164 CHECK (((cmpaltct_mobile_number IS NULL) OR (cmpaltct_mobile_number ~ '^\+[1-9][0-9]{1,14}$'::text))),
    CONSTRAINT ck_company_alternate_contacts__role_not_blank CHECK ((btrim(cmpaltct_role) <> ''::text)),
    CONSTRAINT ck_company_alternate_contacts__work_email_format CHECK (((cmpaltct_work_email)::text ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'::text)),
    CONSTRAINT ck_company_alternate_contacts__work_email_not_blank CHECK ((btrim((cmpaltct_work_email)::text) <> ''::text))
);


--
-- Name: TABLE company_alternate_contacts; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.company_alternate_contacts IS 'Alternate contacts for companies, supporting role-based contact resolution (e.g., BillingContact, DataProtectionContact). Aligns with orderform_alternate_contacts column/contact_type semantics.';


--
-- Name: COLUMN company_alternate_contacts.cmpaltct_role; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_alternate_contacts.cmpaltct_role IS 'Role identifier (e.g., BillingContact, PayProofApprover, DataProtectionContact)';


--
-- Name: COLUMN company_alternate_contacts.cmpaltct_contact_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_alternate_contacts.cmpaltct_contact_type IS 'Contact type: Primary (To recipient), Cc, or Bcc';


--
-- Name: COLUMN company_alternate_contacts.cmpaltct_work_email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.company_alternate_contacts.cmpaltct_work_email IS 'Work email address (RFC 5321 max length)';


--
-- Name: company_alternate_contacts_cmpaltct_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_alternate_contacts ALTER COLUMN cmpaltct_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_alternate_contacts_cmpaltct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_alternate_contacts company_alternate_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_alternate_contacts
    ADD CONSTRAINT company_alternate_contacts_pkey PRIMARY KEY (cmpaltct_id);


--
-- Name: ix_company_alternate_contacts__cmp_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_company_alternate_contacts__cmp_id ON public.company_alternate_contacts USING btree (cmp_id);


--
-- Name: ix_company_alternate_contacts__role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_company_alternate_contacts__role ON public.company_alternate_contacts USING btree (cmpaltct_role);


--
-- Name: company_alternate_contacts trg_update_company_alternate_contacts_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_update_company_alternate_contacts_updated_at BEFORE UPDATE ON public.company_alternate_contacts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: company_alternate_contacts fk_company_alternate_contacts__companies; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_alternate_contacts
    ADD CONSTRAINT fk_company_alternate_contacts__companies FOREIGN KEY (cmp_id) REFERENCES public.companies(cmp_id) ON DELETE RESTRICT;


--
-- Name: company_alternate_contacts; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.company_alternate_contacts ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict HobvfKJyb9BJbLU2m1U6kF8irNLMlrrbR3DH7fSLdgk0iAB4TDTtNOGvGGzgwHe

